import { NextResponse } from 'next/server';
import { desc, eq } from 'drizzle-orm';
import { db } from '@/db/client';
import { auditEvents, dataExportJobs } from '@/db/schema';
import { requireParentSession } from '@/server/auth';
import { audit, context, mapExport, reauthenticate, SafetyError, safetyErrorResponse } from '@/server/safety';
import { z } from 'zod';

export async function GET() { try { const s = await requireParentSession(); if (s instanceof Response) return s; const { household } = await context(s); const rows = await db.select().from(dataExportJobs).where(eq(dataExportJobs.householdId, household.id)).orderBy(desc(dataExportJobs.createdAt)); if (!rows.length) return NextResponse.json({ exports: [] }); const audits = await db.select({ resourceId: auditEvents.resourceId, metadata: auditEvents.metadata }).from(auditEvents).where(eq(auditEvents.eventType, 'data_export.requested')); const requestByJob = new Map(audits.filter((event) => rows.some((row) => row.id === event.resourceId)).map((event) => [event.resourceId, event.metadata as { format?: 'json' | 'csv' | 'zip'; childId?: string } | null])); return NextResponse.json({ exports: rows.map((row) => mapExport(row, requestByJob.get(row.id) ?? undefined)) }); } catch (e) { return safetyErrorResponse(e); } }
const schema = z.object({ childId: z.string().uuid().optional(), includeTranscripts: z.boolean().optional(), includeEmotionTimeline: z.boolean().optional(), includeLearningProgress: z.boolean().optional(), format: z.enum(['json', 'csv', 'zip']).optional(), reauthPassword: z.string().optional() }).strict().refine((p) => p.includeTranscripts === true || p.includeEmotionTimeline === true || p.includeLearningProgress === true, { message: 'Select at least one category to export.' });
export async function POST(request: Request) { try { const s = await requireParentSession(); if (s instanceof Response) return s; const p = schema.safeParse(await request.json()); if (!p.success) throw new SafetyError(400, 'VALIDATION_FAILED', 'Invalid export request.', p.error.flatten().fieldErrors as Record<string, string[]>); const { household } = await context(s); if (p.data.childId) await import('@/server/safety').then(async ({ assertChildOwned }) => assertChildOwned(household.id, p.data.childId)); await reauthenticate(s.sub, p.data.reauthPassword); const format = p.data.format ?? 'zip'; const [row] = await db.insert(dataExportJobs).values({ householdId: household.id, requestedByUserId: s.sub, status: 'pending', stagesCompleted: [] } as typeof dataExportJobs.$inferInsert).returning(); if (!row) throw new Error('Export job insert returned no row'); const requestDetails = { childId: p.data.childId, format, includeTranscripts: p.data.includeTranscripts ?? false, includeEmotionTimeline: p.data.includeEmotionTimeline ?? false, includeLearningProgress: p.data.includeLearningProgress ?? false }; await audit(s.sub, 'data_export.requested', 'data_export_job', row.id, requestDetails); return NextResponse.json({ export: mapExport(row, requestDetails), message: 'Export request is recorded and pending. The safety worker will process it; an object storage adapter must be configured before an archive can be produced.' }, { status: 202 }); } catch (e) { return safetyErrorResponse(e); } }
