import { NextResponse } from 'next/server';
import { and, eq } from 'drizzle-orm';
import { db } from '@/db/client';
import { notificationPreferences, users } from '@/db/schema';
import { requireParentSession } from '@/server/auth';
import { audit, context, SafetyError, safetyErrorResponse } from '@/server/safety';
import { z } from 'zod';

const channels = ['email', 'push', 'in_app'] as const;
async function read(userId: string) {
  const [rows, user] = await Promise.all([db.select().from(notificationPreferences).where(eq(notificationPreferences.userId, userId)), db.select({ email: users.email }).from(users).where(eq(users.id, userId)).limit(1)]);
  const enabled = (channel: string) => rows.find((r) => r.channel === channel)?.enabled ?? false;
  const emailAlerts = enabled('email'), pushAlerts = enabled('push'), weeklyReport = enabled('in_app');
  const channel = emailAlerts && pushAlerts ? 'both' : emailAlerts ? 'email' : pushAlerts ? 'push' : 'none';
  return { emailAlerts, pushAlerts, weeklyReport, emergencySmsAlerts: false, reportCadence: 'weekly' as const, deliveryPreference: { channel, frequency: 'immediate' as const, quietHoursEnabled: false }, ...(user[0]?.email ? { verifiedEmail: user[0].email } : {}), pushDeviceCount: 0, updatedAt: rows.reduce((d, r) => r.updatedAt > d ? r.updatedAt : d, new Date(0)).toISOString() };
}
export async function GET() { try { const s = await requireParentSession(); if (s instanceof Response) return s; await context(s); return NextResponse.json({ preferences: await read(s.sub) }); } catch (e) { return safetyErrorResponse(e); } }
const schema = z.object({ emailAlerts: z.boolean().optional(), pushAlerts: z.boolean().optional(), weeklyReport: z.boolean().optional(), emergencySmsAlerts: z.boolean().optional(), reportCadence: z.enum(['daily', 'weekly', 'monthly']).optional(), deliveryPreference: z.object({ channel: z.enum(['email', 'push', 'both', 'none']).optional(), frequency: z.enum(['immediate', 'digest_daily', 'digest_weekly']).optional(), quietHoursEnabled: z.boolean().optional(), quietHoursStart: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(), quietHoursEnd: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional() }).strict().optional() }).strict();
export async function PATCH(request: Request) { try { const s = await requireParentSession(); if (s instanceof Response) return s; const parsed = schema.safeParse(await request.json()); if (!parsed.success) throw new SafetyError(400, 'VALIDATION_FAILED', 'Invalid notification preferences.', parsed.error.flatten().fieldErrors as Record<string, string[]>); await context(s); const p = parsed.data; if (p.emergencySmsAlerts) throw new SafetyError(503, 'PROVIDER_UNAVAILABLE', 'SMS notifications are unavailable because no delivery provider is configured.'); if (p.reportCadence && p.reportCadence !== 'weekly') throw new SafetyError(503, 'WORKER_UNAVAILABLE', 'Report scheduling is unavailable because no scheduler is configured.'); if (p.deliveryPreference && (p.deliveryPreference.frequency !== undefined && p.deliveryPreference.frequency !== 'immediate' || p.deliveryPreference.quietHoursEnabled || p.deliveryPreference.quietHoursStart || p.deliveryPreference.quietHoursEnd)) throw new SafetyError(503, 'WORKER_UNAVAILABLE', 'Digest and quiet hour scheduling are unavailable because no scheduler is configured.'); const channelValues = { email: p.emailAlerts, push: p.pushAlerts, in_app: p.weeklyReport }; const deliveryChannel = p.deliveryPreference?.channel; if (deliveryChannel) { if (p.emailAlerts === undefined) channelValues.email = deliveryChannel === 'email' || deliveryChannel === 'both'; if (p.pushAlerts === undefined) channelValues.push = deliveryChannel === 'push' || deliveryChannel === 'both'; } for (const channel of channels) { const enabled = channelValues[channel]; if (enabled === undefined) continue; const [existing] = await db.select({ id: notificationPreferences.id }).from(notificationPreferences).where(and(eq(notificationPreferences.userId, s.sub), eq(notificationPreferences.channel, channel))).limit(1); if (existing) await db.update(notificationPreferences).set({ enabled, updatedAt: new Date() } as Partial<typeof notificationPreferences.$inferInsert>).where(eq(notificationPreferences.id, existing.id)); else await db.insert(notificationPreferences).values({ userId: s.sub, channel, enabled, updatedAt: new Date() } as typeof notificationPreferences.$inferInsert); } await audit(s.sub, 'notification_preferences.updated', 'notification_preferences', s.sub, { fields: Object.keys(p) }); return NextResponse.json({ preferences: await read(s.sub) }); } catch (e) { return safetyErrorResponse(e); } }
