import type { CatalogLessonEntry } from '../seed-lessons';

export const createLessonId = (num: number) =>
  `00000000-0000-4000-a000-${num.toString(16).padStart(12, '0')}`;
export const createStepId = (lessonNum: number, stepNum: number) =>
  `00000000-0000-4000-a000-${(lessonNum * 100 + stepNum).toString(16).padStart(12, '0')}`;

export const LITERACY_LESSONS: CatalogLessonEntry[] = [
  // Lesson 1: Làm quen với nguyên âm Tiếng Việt
  {
    lesson: {
      id: createLessonId(1),
      title: 'Làm quen với nguyên âm Tiếng Việt',
      subject: 'Tiếng Việt',
      gradeLevel: 'Mầm non - Lớp 1',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'literacy',
        ageBand: '5-6 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Khám phá các nguyên âm a, o, e, u, i',
        description: 'Bé nhận biết mặt chữ và phát âm chuẩn các nguyên âm cơ bản trong tiếng Việt cùng Snow.',
        image: '/images/lesson-abc.png',
        accent: 'primary',
        rating: '5.0',
        steps: [
          {
            id: createStepId(1, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Chữ cái nào bắt đầu trong từ "Quả Cam"?',
            instruction: 'Chọn chữ cái đúng đại diện cho âm đầu của tiếng thứ hai.',
            helper: 'Lắng nghe âm c trong từ "Cam".',
            explanation: 'Chữ "C" bắt đầu cho từ "Cam" trong tiếng Việt.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-c', label: 'Chữ C', helper: 'C như Con cá, Quả cam' },
              { id: 'opt-a', label: 'Chữ A', helper: 'A như Quả na' },
              { id: 'opt-b', label: 'Chữ B', helper: 'B như Quả bơ' },
            ],
            canonicalAnswer: 'opt-c',
            points: 10,
          },
          {
            id: createStepId(1, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Chữ cái nào có nét tròn như quả trứng gà?',
            instruction: 'Bé hãy nhìn kỹ hình dáng chữ nhé.',
            helper: 'Chữ "O tròn như quả trứng gà".',
            explanation: 'Chữ O có hình tròn xoe đặc trưng.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-o', label: 'Chữ O', helper: 'O tròn như quả trứng gà' },
              { id: 'opt-i', label: 'Chữ I', helper: 'I có một nét thẳng và dấu chấm' },
              { id: 'opt-u', label: 'Chữ U', helper: 'U có nét móc ngược' },
            ],
            canonicalAnswer: 'opt-o',
            points: 10,
          },
          {
            id: createStepId(1, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những chữ cái nào dưới đây là nguyên âm trong tiếng Việt?',
            instruction: 'Chọn tất cả các nguyên âm có trong danh sách.',
            helper: 'Nhớ lại các chữ a, e, o, u, i.',
            explanation: 'A và E là nguyên âm, còn B là phụ âm.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-a-vowel', label: 'Chữ A' },
              { id: 'opt-b-cons', label: 'Chữ B' },
              { id: 'opt-e-vowel', label: 'Chữ E' },
            ],
            canonicalAnswer: ['opt-a-vowel', 'opt-e-vowel'],
            points: 15,
          },
          {
            id: createStepId(1, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Chữ "Ô" là chữ O có thêm chiếc nón trên đầu đúng hay sai?',
            instruction: 'Xem câu nói này đúng hay sai nhé.',
            helper: 'Câu đồng dao: "O tròn như quả trứng gà, Ô thì đội mũ, Ơ thì thêm râu".',
            explanation: 'Chữ Ô chính là chữ O có thêm dấu mũ đội trên đầu.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(1, 5),
            stepOrder: 5,
            questionType: 'fill_blank',
            prompt: 'Điền chữ cái còn thiếu vào chỗ trống: "B... mẹ" (chữ chỉ mẹ hiền)',
            instruction: 'Gõ chữ cái thích hợp vào ô trống.',
            helper: 'Tiếng Ba hoặc tiếng Bố ghép với mẹ.',
            explanation: 'Ta có từ "Ba mẹ".',
            canonicalAnswer: 'a',
            acceptedVariants: ['A'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(1, 1), lessonId: createLessonId(1), stepOrder: 1, stepType: 'question', prompt: 'Chữ cái nào bắt đầu trong từ "Quả Cam"?', correctAnswer: 'opt-c' },
      { id: createStepId(1, 2), lessonId: createLessonId(1), stepOrder: 2, stepType: 'question', prompt: 'Chữ cái nào có nét tròn như quả trứng gà?', correctAnswer: 'opt-o' },
      { id: createStepId(1, 3), lessonId: createLessonId(1), stepOrder: 3, stepType: 'question', prompt: 'Những chữ cái nào dưới đây là nguyên âm trong tiếng Việt?', correctAnswer: JSON.stringify(['opt-a-vowel', 'opt-e-vowel']) },
      { id: createStepId(1, 4), lessonId: createLessonId(1), stepOrder: 4, stepType: 'question', prompt: 'Chữ "Ô" là chữ O có thêm chiếc nón trên đầu đúng hay sai?', correctAnswer: 'true' },
      { id: createStepId(1, 5), lessonId: createLessonId(1), stepOrder: 5, stepType: 'question', prompt: 'Điền chữ cái còn thiếu vào chỗ trống: "B... mẹ"', correctAnswer: 'a' },
    ],
  },

  // Lesson 2: Dấu thanh diệu kỳ trong Tiếng Việt
  {
    lesson: {
      id: createLessonId(2),
      title: 'Dấu thanh diệu kỳ trong Tiếng Việt',
      subject: 'Tiếng Việt',
      gradeLevel: 'Lớp 1',
      estimatedMinutes: 15,
      isPublished: true,
      content: JSON.stringify({
        track: 'literacy',
        ageBand: '6-7 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Sắc, huyền, hỏi, ngã, nặng',
        description: 'Học cách nhận biết 5 dấu thanh và thanh ngang giúp biến đổi nghĩa của tiếng.',
        image: '/images/lesson-abc.png',
        accent: 'primary',
        rating: '4.9',
        steps: [
          {
            id: createStepId(2, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Dấu thanh nào có hình nét xiên sang phải (ví dụ trong chữ "Cá")?',
            instruction: 'Chọn tên gọi chính xác của dấu thanh.',
            helper: 'Dấu sắc nghiêng lên về phía bên phải.',
            explanation: 'Dấu sắc có nét xiên từ trái qua phải đi lên.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-sac', label: 'Dấu sắc' },
              { id: 'opt-huyen', label: 'Dấu huyền' },
              { id: 'opt-nang', label: 'Dấu nặng' },
            ],
            canonicalAnswer: 'opt-sac',
            points: 10,
          },
          {
            id: createStepId(2, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Chữ "Cà" trong quả cà mang dấu thanh gì?',
            instruction: 'Nhìn dấu thanh trên đầu chữ a.',
            helper: 'Dấu nghiêng từ phải xuống trái.',
            explanation: 'Chữ "Cà" mang dấu huyền.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-huyen', label: 'Dấu huyền' },
              { id: 'opt-hoi', label: 'Dấu hỏi' },
              { id: 'opt-nga', label: 'Dấu ngã' },
            ],
            canonicalAnswer: 'opt-huyen',
            points: 10,
          },
          {
            id: createStepId(2, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những từ nào dưới đây mang dấu hỏi?',
            instruction: 'Chọn tất cả các từ có dấu hỏi.',
            helper: 'Dấu hỏi giống hình chiếc móc câu nhỏ.',
            explanation: '"Quả bưởi" và "Cái rổ" đều mang dấu hỏi.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-buoi', label: 'Quả bưởi' },
              { id: 'opt-ca', label: 'Con cá' },
              { id: 'opt-ro', label: 'Cái rổ' },
            ],
            canonicalAnswer: ['opt-buoi', 'opt-ro'],
            points: 15,
          },
          {
            id: createStepId(2, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Tiếng Việt có tổng cộng 5 dấu thanh (sắc, huyền, hỏi, ngã, nặng) và thanh ngang (không dấu), đúng hay sai?',
            instruction: 'Xác định tính đúng đắn của nhận định.',
            helper: 'Đếm lại các dấu thanh nhé.',
            explanation: 'Đúng, tiếng Việt có 6 thanh: ngang, huyền, sắc, hỏi, ngã, nặng.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(2, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Gõ từ "bút" khi có dấu sắc:',
            instruction: 'Nhập chính xác từ "bút" có dấu sắc.',
            helper: 'Dùng bàn phím gõ chữ b-u-t với dấu sắc.',
            explanation: 'Từ chính xác là "bút".',
            canonicalAnswer: 'bút',
            acceptedVariants: ['Bút', 'BÚT'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(2, 1), lessonId: createLessonId(2), stepOrder: 1, stepType: 'question', prompt: 'Dấu thanh nào có hình nét xiên sang phải?', correctAnswer: 'opt-sac' },
      { id: createStepId(2, 2), lessonId: createLessonId(2), stepOrder: 2, stepType: 'question', prompt: 'Chữ "Cà" mang dấu thanh gì?', correctAnswer: 'opt-huyen' },
      { id: createStepId(2, 3), lessonId: createLessonId(2), stepOrder: 3, stepType: 'question', prompt: 'Những từ nào dưới đây mang dấu hỏi?', correctAnswer: JSON.stringify(['opt-buoi', 'opt-ro']) },
      { id: createStepId(2, 4), lessonId: createLessonId(2), stepOrder: 4, stepType: 'question', prompt: 'Hệ thống thanh điệu tiếng Việt gồm 6 thanh đúng hay sai?', correctAnswer: 'true' },
      { id: createStepId(2, 5), lessonId: createLessonId(2), stepOrder: 5, stepType: 'question', prompt: 'Gõ từ "bút" khi có dấu sắc:', correctAnswer: 'bút' },
    ],
  },

  // Lesson 3: Ghép vần đơn giản: Ba, Bố, Mẹ, Bé
  {
    lesson: {
      id: createLessonId(3),
      title: 'Ghép vần gia đình yêu thương',
      subject: 'Tiếng Việt',
      gradeLevel: 'Lớp 1',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'literacy',
        ageBand: '6-7 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Đọc và ghép các từ gia đình quen thuộc',
        description: 'Tập ghép âm đầu và vần để gọi tên những người thân yêu nhất trong nhà.',
        image: '/images/lesson-abc.png',
        accent: 'primary',
        rating: '4.8',
        steps: [
          {
            id: createStepId(3, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Âm "b" ghép với âm "e" và dấu sắc tạo thành tiếng gì?',
            instruction: 'Ghép âm b-e sắc.',
            helper: 'Em bé đáng yêu.',
            explanation: 'Âm b + e + sắc = bé.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-be', label: 'Bé' },
              { id: 'opt-ba', label: 'Bà' },
              { id: 'opt-bo', label: 'Bố' },
            ],
            canonicalAnswer: 'opt-be',
            points: 10,
          },
          {
            id: createStepId(3, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp các chữ cái để tạo thành từ "MẸ":',
            instruction: 'Kéo thả hoặc sắp thứ tự các chữ cái.',
            helper: 'Bắt đầu bằng chữ M.',
            explanation: 'Thứ tự đúng là M rồi đến Ẹ.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'let-m', label: 'Chữ M' },
              { id: 'let-e-dot', label: 'Chữ Ẹ' },
            ],
            canonicalAnswer: ['let-m', 'let-e-dot'],
            points: 15,
          },
          {
            id: createStepId(3, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những từ nào là từ chỉ người thân trong gia đình?',
            instruction: 'Chọn tất cả các đáp án đúng.',
            helper: 'Những người cùng chung sống dưới một mái nhà.',
            explanation: 'Ông bà và Cha mẹ là người thân gia đình.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-ongba', label: 'Ông bà' },
              { id: 'opt-chame', label: 'Cha mẹ' },
              { id: 'opt-xehoi', label: 'Xe hơi' },
            ],
            canonicalAnswer: ['opt-ongba', 'opt-chame'],
            points: 15,
          },
          {
            id: createStepId(3, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Từ "Gia đình" có nghĩa là tổ ấm yêu thương của bé đúng hay sai?',
            instruction: 'Chọn đúng hoặc sai.',
            helper: 'Nơi mọi người luôn chăm sóc và bảo vệ nhau.',
            explanation: 'Đúng, gia đình là tổ ấm che chở cho mỗi đứa trẻ.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(3, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Gõ từ "bố" bằng chữ thường:',
            instruction: 'Nhập từ "bố" đầy đủ dấu tiếng Việt.',
            helper: 'B-ố.',
            explanation: 'Từ chuẩn tiếng Việt là "bố".',
            canonicalAnswer: 'bố',
            acceptedVariants: ['Bố', 'bô'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(3, 1), lessonId: createLessonId(3), stepOrder: 1, stepType: 'question', prompt: 'Âm b + e + sắc tạo thành tiếng gì?', correctAnswer: 'opt-be' },
      { id: createStepId(3, 2), lessonId: createLessonId(3), stepOrder: 2, stepType: 'question', prompt: 'Sắp xếp các chữ tạo từ MẸ', correctAnswer: JSON.stringify(['let-m', 'let-e-dot']) },
      { id: createStepId(3, 3), lessonId: createLessonId(3), stepOrder: 3, stepType: 'question', prompt: 'Từ chỉ người thân trong gia đình', correctAnswer: JSON.stringify(['opt-ongba', 'opt-chame']) },
      { id: createStepId(3, 4), lessonId: createLessonId(3), stepOrder: 4, stepType: 'question', prompt: 'Ý nghĩa của gia đình', correctAnswer: 'true' },
      { id: createStepId(3, 5), lessonId: createLessonId(3), stepOrder: 5, stepType: 'question', prompt: 'Gõ từ bố', correctAnswer: 'bố' },
    ],
  },

  // Lesson 4: Từ trái nghĩa vui nhộn
  {
    lesson: {
      id: createLessonId(4),
      title: 'Từ trái nghĩa vui nhộn',
      subject: 'Tiếng Việt',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 14,
      isPublished: true,
      content: JSON.stringify({
        track: 'literacy',
        ageBand: '6-8 tuổi',
        difficulty: 'Trung bình',
        subtitle: 'Lớn - bé, cao - thấp, nhanh - chậm',
        description: 'Mở rộng vốn từ vựng miêu tả qua các cặp từ trái ngược nhau thật sinh động.',
        image: '/images/lesson-abc.png',
        accent: 'primary',
        rating: '4.9',
        steps: [
          {
            id: createStepId(4, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Từ nào trái nghĩa với từ "Cao"?',
            instruction: 'Chọn từ có ý nghĩa đối lập với "Cao".',
            helper: 'Ví dụ: Cây dừa rất cao, còn bụi cỏ thì...',
            explanation: 'Từ trái nghĩa với "Cao" là "Thấp".',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-thap', label: 'Thấp' },
              { id: 'opt-to', label: 'To' },
              { id: 'opt-dai', label: 'Dài' },
            ],
            canonicalAnswer: 'opt-thap',
            points: 10,
          },
          {
            id: createStepId(4, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Chú rùa bò rất chậm, còn chú thỏ chạy rất...?',
            instruction: 'Điền từ trái nghĩa với "chậm".',
            helper: 'Thỏ chạy vun vút.',
            explanation: 'Nhanh đối lập với chậm.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-nhanh', label: 'Nhanh' },
              { id: 'opt-khe', label: 'Khẽ' },
              { id: 'opt-yeu', label: 'Yếu' },
            ],
            canonicalAnswer: 'opt-nhanh',
            points: 10,
          },
          {
            id: createStepId(4, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những cặp từ nào dưới đây là cặp từ trái nghĩa?',
            instruction: 'Chọn tất cả các cặp từ trái nghĩa đúng.',
            helper: 'Hai từ phải chỉ hai tính chất đối lập nhau.',
            explanation: '"Nóng - Lạnh" và "Ngày - Đêm" là các cặp từ trái nghĩa.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-nong-lanh', label: 'Nóng - Lạnh' },
              { id: 'opt-ngay-dem', label: 'Ngày - Đêm' },
              { id: 'opt-vui-mung', label: 'Vui vẻ - Mừng rỡ' },
            ],
            canonicalAnswer: ['opt-nong-lanh', 'opt-ngay-dem'],
            points: 15,
          },
          {
            id: createStepId(4, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: '"Sáng" và "Tối" là một cặp từ trái nghĩa, đúng hay sai?',
            instruction: 'Xác định quan hệ ý nghĩa giữa hai từ.',
            helper: 'Ban ngày trời sáng, ban đêm trời tối.',
            explanation: 'Đúng, sáng và tối biểu thị hai trạng thái ánh sáng đối lập.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(4, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Từ trái nghĩa với từ "Bé" là gì? (Gõ 1 từ)',
            instruction: 'Nhập từ đơn trái nghĩa với "Bé".',
            helper: 'Ví dụ: Quả dưa hấu rất to, quả nho rất bé.',
            explanation: '"To" hoặc "Lớn" là từ trái nghĩa với "Bé".',
            canonicalAnswer: 'to',
            acceptedVariants: ['lớn', 'To', 'Lớn'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(4, 1), lessonId: createLessonId(4), stepOrder: 1, stepType: 'question', prompt: 'Từ trái nghĩa với "Cao"', correctAnswer: 'opt-thap' },
      { id: createStepId(4, 2), lessonId: createLessonId(4), stepOrder: 2, stepType: 'question', prompt: 'Từ trái nghĩa với "Chậm"', correctAnswer: 'opt-nhanh' },
      { id: createStepId(4, 3), lessonId: createLessonId(4), stepOrder: 3, stepType: 'question', prompt: 'Các cặp từ trái nghĩa', correctAnswer: JSON.stringify(['opt-nong-lanh', 'opt-ngay-dem']) },
      { id: createStepId(4, 4), lessonId: createLessonId(4), stepOrder: 4, stepType: 'question', prompt: 'Sáng và Tối là từ trái nghĩa đúng hay sai', correctAnswer: 'true' },
      { id: createStepId(4, 5), lessonId: createLessonId(4), stepOrder: 5, stepType: 'question', prompt: 'Từ trái nghĩa với Bé', correctAnswer: 'to' },
    ],
  },

  // Lesson 5: Mở rộng câu: Ai làm gì?
  {
    lesson: {
      id: createLessonId(5),
      title: 'Mẫu câu: Ai làm gì?',
      subject: 'Tiếng Việt',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 15,
      isPublished: true,
      content: JSON.stringify({
        track: 'literacy',
        ageBand: '6-8 tuổi',
        difficulty: 'Trung bình',
        subtitle: 'Cấu trúc câu kể hành động quen thuộc',
        description: 'Tập đặt câu kể về hành động của con người, con vật xung quanh bé.',
        image: '/images/lesson-abc.png',
        accent: 'primary',
        rating: '4.8',
        steps: [
          {
            id: createStepId(5, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Trong câu "Bé đang đọc sách", từ nào chỉ hành động?',
            instruction: 'Tìm từ chỉ hoạt động của bạn nhỏ.',
            helper: 'Bạn nhỏ đang làm việc gì với quyển sách?',
            explanation: '"Đọc sách" là cụm từ chỉ hành động.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-doc', label: 'Đọc sách' },
              { id: 'opt-be', label: 'Bé' },
              { id: 'opt-sach', label: 'Quyển sách' },
            ],
            canonicalAnswer: 'opt-doc',
            points: 10,
          },
          {
            id: createStepId(5, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp các từ thành câu hoàn chỉnh theo mẫu "Ai làm gì?":',
            instruction: 'Kéo thả các từ theo đúng trật tự ngữ pháp.',
            helper: 'Người thực hiện hành động đứng đầu câu.',
            explanation: 'Trật tự đúng: Chú chim -> hót -> véo von.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'w-chim', label: 'Chú chim' },
              { id: 'w-hot', label: 'hót' },
              { id: 'w-veovon', label: 'véo von.' },
            ],
            canonicalAnswer: ['w-chim', 'w-hot', 'w-veovon'],
            points: 15,
          },
          {
            id: createStepId(5, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những câu nào dưới đây thuộc mẫu câu "Ai làm gì?"',
            instruction: 'Chọn tất cả các câu kể về hoạt động.',
            helper: 'Câu phải có chủ ngữ và từ chỉ hành động.',
            explanation: '"Mẹ nấu cơm" và "Bác nông dân gặt lúa" kể về hành động.',
            image: '/images/lesson-abc.png',
            options: [
              { id: 'opt-me-nau', label: 'Mẹ đang nấu cơm.' },
              { id: 'opt-bong-hoa', label: 'Bông hoa rất đẹp.' },
              { id: 'opt-bac-gat', label: 'Bác nông dân gặt lúa.' },
            ],
            canonicalAnswer: ['opt-me-nau', 'opt-bac-gat'],
            points: 15,
          },
          {
            id: createStepId(5, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Câu "Bầu trời màu xanh biếc" là câu theo mẫu "Ai làm gì?", đúng hay sai?',
            instruction: 'Xem câu này có từ chỉ hành động không nhé.',
            helper: '"Xanh biếc" là từ chỉ màu sắc, đặc điểm, không phải hành động.',
            explanation: 'Sai, câu này thuộc mẫu câu "Ai thế nào?".',
            canonicalAnswer: false,
            points: 10,
          },
          {
            id: createStepId(5, 5),
            stepOrder: 5,
            questionType: 'fill_blank',
            prompt: 'Điền từ chỉ hành động thích hợp: "Cá vàng ... tung tăng trong bể nước."',
            instruction: 'Gõ từ chỉ cách di chuyển của loài cá dưới nước.',
            helper: 'Cá dùng vây và đuôi để làm gì?',
            explanation: 'Từ chính xác là "bơi".',
            canonicalAnswer: 'bơi',
            acceptedVariants: ['bơi lội', 'Bơi'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(5, 1), lessonId: createLessonId(5), stepOrder: 1, stepType: 'question', prompt: 'Từ chỉ hành động trong câu', correctAnswer: 'opt-doc' },
      { id: createStepId(5, 2), lessonId: createLessonId(5), stepOrder: 2, stepType: 'question', prompt: 'Sắp xếp câu Chú chim hót véo von', correctAnswer: JSON.stringify(['w-chim', 'w-hot', 'w-veovon']) },
      { id: createStepId(5, 3), lessonId: createLessonId(5), stepOrder: 3, stepType: 'question', prompt: 'Xác định câu mẫu Ai làm gì', correctAnswer: JSON.stringify(['opt-me-nau', 'opt-bac-gat']) },
      { id: createStepId(5, 4), lessonId: createLessonId(5), stepOrder: 4, stepType: 'question', prompt: 'Bầu trời màu xanh biếc là câu Ai làm gì đúng hay sai', correctAnswer: 'false' },
      { id: createStepId(5, 5), lessonId: createLessonId(5), stepOrder: 5, stepType: 'question', prompt: 'Điền từ hành động của cá vàng', correctAnswer: 'bơi' },
    ],
  },
];
