import type { CatalogLessonEntry } from '../seed-lessons';
import { createLessonId, createStepId } from './literacy';

export const MATHEMATICS_LESSONS: CatalogLessonEntry[] = [
  // Lesson 6: Đếm vui từ 1 đến 10 cùng các bạn nhỏ
  {
    lesson: {
      id: createLessonId(6),
      title: 'Đếm vui từ 1 đến 10',
      subject: 'Toán học',
      gradeLevel: 'Mầm non - Lớp 1',
      estimatedMinutes: 10,
      isPublished: true,
      content: JSON.stringify({
        track: 'mathematics',
        ageBand: '5-6 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Nhận biết số lượng và chữ số từ 1 đến 10',
        description: 'Luyện tập đếm đồ vật, con vật dễ thương trong phạm vi 10 cùng Snow.',
        image: '/images/lesson-math.png',
        accent: 'aqua',
        rating: '5.0',
        steps: [
          {
            id: createStepId(6, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Có bao nhiêu ngón tay trên một bàn tay bình thường của chúng ta?',
            instruction: 'Xòe bàn tay và đếm cùng Snow nhé.',
            helper: 'Ngón cái, ngón trỏ, ngón giữa, ngón áp út, ngón út.',
            explanation: 'Một bàn tay có 5 ngón tay.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-5', label: '5 ngón tay' },
              { id: 'opt-4', label: '4 ngón tay' },
              { id: 'opt-6', label: '6 ngón tay' },
            ],
            canonicalAnswer: 'opt-5',
            points: 10,
          },
          {
            id: createStepId(6, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp các số sau theo thứ tự tăng dần từ bé đến lớn:',
            instruction: 'Chọn thứ tự đúng của các số: 2, 4, 1, 3.',
            helper: 'Bắt đầu từ số nhỏ nhất là số 1.',
            explanation: 'Thứ tự tăng dần là: 1, 2, 3, 4.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'num-1', label: 'Số 1' },
              { id: 'num-2', label: 'Số 2' },
              { id: 'num-3', label: 'Số 3' },
              { id: 'num-4', label: 'Số 4' },
            ],
            canonicalAnswer: ['num-1', 'num-2', 'num-3', 'num-4'],
            points: 15,
          },
          {
            id: createStepId(6, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những số nào dưới đây lớn hơn 5 và nhỏ hơn 9?',
            instruction: 'Chọn tất cả các số nằm giữa 5 và 9.',
            helper: 'Đếm tiếp sau 5: 6, 7, 8.',
            explanation: 'Các số lớn hơn 5 và nhỏ hơn 9 là 6 và 7.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-6', label: 'Số 6' },
              { id: 'opt-7', label: 'Số 7' },
              { id: 'opt-10', label: 'Số 10' },
            ],
            canonicalAnswer: ['opt-6', 'opt-7'],
            points: 15,
          },
          {
            id: createStepId(6, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Số 0 là số biểu thị không có đồ vật nào, đúng hay sai?',
            instruction: 'Xác định ý nghĩa của chữ số 0.',
            helper: 'Khi trong giỏ không còn quả táo nào, số lượng táo là 0.',
            explanation: 'Đúng, số 0 đại diện cho tập hợp rỗng, không có phần tử nào.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(6, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Số liền sau của số 9 là số nào? (Gõ chữ số)',
            instruction: 'Nhập chữ số liền kề ngay sau số 9.',
            helper: '9 thêm 1 là mấy?',
            explanation: 'Số liền sau số 9 là số 10.',
            canonicalAnswer: '10',
            acceptedVariants: ['mười', 'Mười'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(6, 1), lessonId: createLessonId(6), stepOrder: 1, stepType: 'question', prompt: 'Số ngón tay trên một bàn tay', correctAnswer: 'opt-5' },
      { id: createStepId(6, 2), lessonId: createLessonId(6), stepOrder: 2, stepType: 'question', prompt: 'Sắp xếp dãy số 1 2 3 4', correctAnswer: JSON.stringify(['num-1', 'num-2', 'num-3', 'num-4']) },
      { id: createStepId(6, 3), lessonId: createLessonId(6), stepOrder: 3, stepType: 'question', prompt: 'Số lớn hơn 5 và nhỏ hơn 9', correctAnswer: JSON.stringify(['opt-6', 'opt-7']) },
      { id: createStepId(6, 4), lessonId: createLessonId(6), stepOrder: 4, stepType: 'question', prompt: 'Ý nghĩa số 0', correctAnswer: 'true' },
      { id: createStepId(6, 5), lessonId: createLessonId(6), stepOrder: 5, stepType: 'question', prompt: 'Số liền sau của số 9', correctAnswer: '10' },
    ],
  },

  // Lesson 7: Phép cộng nhẹ nhàng trong phạm vi 10
  {
    lesson: {
      id: createLessonId(7),
      title: 'Phép cộng nhẹ nhàng trong phạm vi 10',
      subject: 'Toán học',
      gradeLevel: 'Lớp 1',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'mathematics',
        ageBand: '6-7 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Cộng gộp đồ vật và que tính vui vẻ',
        description: 'Làm quen với dấu cộng (+) và tính nhẩm tổng các số nhỏ trong phạm vi 10.',
        image: '/images/lesson-math.png',
        accent: 'aqua',
        rating: '4.9',
        steps: [
          {
            id: createStepId(7, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Bé có 3 quả táo đỏ, bạn tặng bé thêm 2 quả táo xanh. Hỏi bé có tất cả mấy quả táo?',
            instruction: 'Thực hiện phép tính 3 + 2.',
            helper: 'Đếm tiếp từ 3: 4, 5.',
            explanation: '3 + 2 = 5 quả táo.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-5', label: '5 quả táo' },
              { id: 'opt-6', label: '6 quả táo' },
              { id: 'opt-4', label: '4 quả táo' },
            ],
            canonicalAnswer: 'opt-5',
            points: 10,
          },
          {
            id: createStepId(7, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Kết quả của phép tính 4 + 4 bằng bao nhiêu?',
            instruction: 'Tính tổng của 4 và 4.',
            helper: '4 thêm 4 bằng mấy?',
            explanation: '4 + 4 = 8.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-8', label: '8' },
              { id: 'opt-7', label: '7' },
              { id: 'opt-9', label: '9' },
            ],
            canonicalAnswer: 'opt-8',
            points: 10,
          },
          {
            id: createStepId(7, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những phép cộng nào dưới đây có kết quả bằng 10?',
            instruction: 'Chọn tất cả các phép tính có tổng là 10.',
            helper: 'Các cặp số tạo thành 10: 5+5, 3+7, 2+8...',
            explanation: '5 + 5 = 10 và 7 + 3 = 10.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-5-5', label: '5 + 5' },
              { id: 'opt-7-3', label: '7 + 3' },
              { id: 'opt-4-5', label: '4 + 5' },
            ],
            canonicalAnswer: ['opt-5-5', 'opt-7-3'],
            points: 15,
          },
          {
            id: createStepId(7, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Khi đổi chỗ hai số trong phép cộng (ví dụ 2 + 3 và 3 + 2), kết quả không thay đổi, đúng hay sai?',
            instruction: 'Tính chất giao hoán của phép cộng.',
            helper: '2 + 3 = 5 và 3 + 2 cũng bằng 5.',
            explanation: 'Đúng, phép cộng có tính chất giao hoán.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(7, 5),
            stepOrder: 5,
            questionType: 'fill_blank',
            prompt: 'Điền số thích hợp: 6 + ... = 9 (Gõ chữ số)',
            instruction: 'Tìm số còn thiếu trong phép tính.',
            helper: '6 thêm mấy thì được 9?',
            explanation: '6 + 3 = 9.',
            canonicalAnswer: '3',
            acceptedVariants: ['ba', 'Ba'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(7, 1), lessonId: createLessonId(7), stepOrder: 1, stepType: 'question', prompt: 'Tính 3 + 2', correctAnswer: 'opt-5' },
      { id: createStepId(7, 2), lessonId: createLessonId(7), stepOrder: 2, stepType: 'question', prompt: 'Tính 4 + 4', correctAnswer: 'opt-8' },
      { id: createStepId(7, 3), lessonId: createLessonId(7), stepOrder: 3, stepType: 'question', prompt: 'Các phép tính có tổng bằng 10', correctAnswer: JSON.stringify(['opt-5-5', 'opt-7-3']) },
      { id: createStepId(7, 4), lessonId: createLessonId(7), stepOrder: 4, stepType: 'question', prompt: 'Tính chất đổi chỗ phép cộng', correctAnswer: 'true' },
      { id: createStepId(7, 5), lessonId: createLessonId(7), stepOrder: 5, stepType: 'question', prompt: 'Điền số 6 + ... = 9', correctAnswer: '3' },
    ],
  },

  // Lesson 8: Phép trừ và tách số trong phạm vi 10
  {
    lesson: {
      id: createLessonId(8),
      title: 'Phép trừ và bài toán bớt đi',
      subject: 'Toán học',
      gradeLevel: 'Lớp 1',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'mathematics',
        ageBand: '6-7 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Làm quen với dấu trừ (-) và bớt số',
        description: 'Hiểu bản chất của phép trừ qua các tình huống thực tế bớt đi đồ vật.',
        image: '/images/lesson-math.png',
        accent: 'aqua',
        rating: '4.8',
        steps: [
          {
            id: createStepId(8, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Trên cành cây có 5 chú chim, 2 chú chim bay đi mất. Hỏi trên cành còn lại mấy chú chim?',
            instruction: 'Thực hiện phép tính 5 - 2.',
            helper: '5 bớt 2 còn lại mấy chú chim?',
            explanation: '5 - 2 = 3 chú chim.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-3', label: '3 chú chim' },
              { id: 'opt-2', label: '2 chú chim' },
              { id: 'opt-4', label: '4 chú chim' },
            ],
            canonicalAnswer: 'opt-3',
            points: 10,
          },
          {
            id: createStepId(8, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Kết quả của phép trừ 8 - 3 bằng bao nhiêu?',
            instruction: 'Tính hiệu số của 8 và 3.',
            helper: 'Đếm lùi từ 8: 7, 6, 5.',
            explanation: '8 - 3 = 5.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-5', label: '5' },
              { id: 'opt-4', label: '4' },
              { id: 'opt-6', label: '6' },
            ],
            canonicalAnswer: 'opt-5',
            points: 10,
          },
          {
            id: createStepId(8, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những phép trừ nào dưới đây có kết quả bằng 4?',
            instruction: 'Chọn tất cả các phép tính đúng.',
            helper: 'Kiểm tra từng phép trừ.',
            explanation: '10 - 6 = 4 và 7 - 3 = 4.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-10-6', label: '10 - 6' },
              { id: 'opt-7-3', label: '7 - 3' },
              { id: 'opt-9-4', label: '9 - 4' },
            ],
            canonicalAnswer: ['opt-10-6', 'opt-7-3'],
            points: 15,
          },
          {
            id: createStepId(8, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Bất kỳ số nào trừ đi chính nó cũng cho kết quả bằng 0 (ví dụ: 7 - 7 = 0), đúng hay sai?',
            instruction: 'Xác định quy luật trừ đi chính nó.',
            helper: 'Có 7 viên kẹo, ăn hết 7 viên kẹo thì còn lại gì không?',
            explanation: 'Đúng, a - a = 0 với mọi số a.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(8, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Kết quả của phép tính 10 - 5 là bao nhiêu? (Gõ chữ số)',
            instruction: 'Nhập kết quả phép trừ.',
            helper: 'Một nửa của 10.',
            explanation: '10 - 5 = 5.',
            canonicalAnswer: '5',
            acceptedVariants: ['năm', 'Năm'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(8, 1), lessonId: createLessonId(8), stepOrder: 1, stepType: 'question', prompt: 'Tính 5 chú chim bay mất 2', correctAnswer: 'opt-3' },
      { id: createStepId(8, 2), lessonId: createLessonId(8), stepOrder: 2, stepType: 'question', prompt: 'Tính 8 - 3', correctAnswer: 'opt-5' },
      { id: createStepId(8, 3), lessonId: createLessonId(8), stepOrder: 3, stepType: 'question', prompt: 'Các phép trừ có kết quả bằng 4', correctAnswer: JSON.stringify(['opt-10-6', 'opt-7-3']) },
      { id: createStepId(8, 4), lessonId: createLessonId(8), stepOrder: 4, stepType: 'question', prompt: 'Số trừ đi chính nó bằng 0', correctAnswer: 'true' },
      { id: createStepId(8, 5), lessonId: createLessonId(8), stepOrder: 5, stepType: 'question', prompt: 'Tính 10 - 5', correctAnswer: '5' },
    ],
  },

  // Lesson 9: Hình học quanh em: Tròn, vuông, tam giác, chữ nhật
  {
    lesson: {
      id: createLessonId(9),
      title: 'Thế giới hình học quanh em',
      subject: 'Toán học',
      gradeLevel: 'Lớp 1',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'mathematics',
        ageBand: '6-7 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Nhận biết các hình phẳng quen thuộc',
        description: 'Quan sát các đồ vật trong đời sống và nhận diện hình tròn, hình vuông, tam giác.',
        image: '/images/lesson-math.png',
        accent: 'aqua',
        rating: '4.9',
        steps: [
          {
            id: createStepId(9, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Mặt đồng hồ treo tường hay chiếc bánh pizza thường có hình gì?',
            instruction: 'Chọn hình dạng tương ứng.',
            helper: 'Hình có đường cong khép kín tròn xoe.',
            explanation: 'Bánh pizza và đồng hồ tròn có hình tròn.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-tron', label: 'Hình tròn' },
              { id: 'opt-vuong', label: 'Hình vuông' },
              { id: 'opt-tamgiac', label: 'Hình tam giác' },
            ],
            canonicalAnswer: 'opt-tron',
            points: 10,
          },
          {
            id: createStepId(9, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Hình tam giác có bao nhiêu cạnh và bao nhiêu góc?',
            instruction: 'Đếm số cạnh của hình tam giác.',
            helper: '"Tam" nghĩa là ba trong tiếng Hán Việt.',
            explanation: 'Hình tam giác có 3 cạnh và 3 góc.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-3', label: '3 cạnh' },
              { id: 'opt-4', label: '4 cạnh' },
              { id: 'opt-5', label: '5 cạnh' },
            ],
            canonicalAnswer: 'opt-3',
            points: 10,
          },
          {
            id: createStepId(9, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những hình nào dưới đây có 4 cạnh?',
            instruction: 'Chọn tất cả các hình có 4 cạnh.',
            helper: 'Hình vuông và hình chữ nhật đều có 4 cạnh.',
            explanation: 'Hình vuông và hình chữ nhật đều là hình tứ giác có 4 cạnh.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-vuong', label: 'Hình vuông' },
              { id: 'opt-chunhat', label: 'Hình chữ nhật' },
              { id: 'opt-tamgiac', label: 'Hình tam giác' },
            ],
            canonicalAnswer: ['opt-vuong', 'opt-chunhat'],
            points: 15,
          },
          {
            id: createStepId(9, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Hình vuông có 4 cạnh dài bằng nhau, đúng hay sai?',
            instruction: 'Xác định đặc điểm của hình vuông.',
            helper: 'Cả 4 cạnh của hình vuông đều có độ dài như nhau.',
            explanation: 'Đúng, hình vuông có 4 góc vuông và 4 cạnh bằng nhau.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(9, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Khung của cánh cửa ra vào phòng học thường có hình gì? (Gõ: chữ nhật, vuông hoặc tròn)',
            instruction: 'Nhập tên hình dạng phổ biến của cánh cửa.',
            helper: 'Có 2 cạnh dài và 2 cạnh ngắn.',
            explanation: 'Cánh cửa thường có dạng hình chữ nhật.',
            canonicalAnswer: 'chữ nhật',
            acceptedVariants: ['hình chữ nhật', 'Hình chữ nhật', 'chu nhat'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(9, 1), lessonId: createLessonId(9), stepOrder: 1, stepType: 'question', prompt: 'Bánh pizza có hình gì', correctAnswer: 'opt-tron' },
      { id: createStepId(9, 2), lessonId: createLessonId(9), stepOrder: 2, stepType: 'question', prompt: 'Số cạnh của hình tam giác', correctAnswer: 'opt-3' },
      { id: createStepId(9, 3), lessonId: createLessonId(9), stepOrder: 3, stepType: 'question', prompt: 'Các hình có 4 cạnh', correctAnswer: JSON.stringify(['opt-vuong', 'opt-chunhat']) },
      { id: createStepId(9, 4), lessonId: createLessonId(9), stepOrder: 4, stepType: 'question', prompt: 'Đặc điểm 4 cạnh hình vuông', correctAnswer: 'true' },
      { id: createStepId(9, 5), lessonId: createLessonId(9), stepOrder: 5, stepType: 'question', prompt: 'Hình dạng của cánh cửa', correctAnswer: 'chữ nhật' },
    ],
  },

  // Lesson 10: Xem giờ đúng trên đồng hồ kim
  {
    lesson: {
      id: createLessonId(10),
      title: 'Bé tập xem đồng hồ',
      subject: 'Toán học',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 14,
      isPublished: true,
      content: JSON.stringify({
        track: 'mathematics',
        ageBand: '6-8 tuổi',
        difficulty: 'Trung bình',
        subtitle: 'Giờ đúng và sinh hoạt hàng ngày',
        description: 'Tập xem kim ngắn chỉ giờ, kim dài chỉ phút để biết thời gian sinh hoạt chuẩn mực.',
        image: '/images/lesson-math.png',
        accent: 'aqua',
        rating: '4.8',
        steps: [
          {
            id: createStepId(10, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Trên mặt đồng hồ, kim ngắn chỉ cái gì và kim dài chỉ cái gì?',
            instruction: 'Chọn câu miêu tả đúng chức năng hai kim.',
            helper: 'Kim ngắn đi chậm chỉ giờ.',
            explanation: 'Kim ngắn chỉ giờ, kim dài chỉ phút.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-gio-phut', label: 'Kim ngắn chỉ giờ, kim dài chỉ phút' },
              { id: 'opt-phut-gio', label: 'Kim ngắn chỉ phút, kim dài chỉ giờ' },
              { id: 'opt-giay', label: 'Cả hai kim đều chỉ giây' },
            ],
            canonicalAnswer: 'opt-gio-phut',
            points: 10,
          },
          {
            id: createStepId(10, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Khi kim dài chỉ đúng số 12 và kim ngắn chỉ số 7, đồng hồ chỉ mấy giờ?',
            instruction: 'Xác định giờ đúng trên mặt đồng hồ.',
            helper: 'Kim dài số 12 là giờ đúng.',
            explanation: 'Đồng hồ chỉ đúng 7 giờ.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-7h', label: '7 giờ đúng' },
              { id: 'opt-12h', label: '12 giờ đúng' },
              { id: 'opt-6h', label: '6 giờ đúng' },
            ],
            canonicalAnswer: 'opt-7h',
            points: 10,
          },
          {
            id: createStepId(10, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Một ngày có bao nhiêu giờ và gồm những buổi nào?',
            instruction: 'Chọn các nhận định đúng về thời gian trong ngày.',
            helper: 'Một ngày đêm trọn vẹn.',
            explanation: 'Một ngày có 24 giờ và chia thành sáng, trưa, chiều, tối.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-24h', label: 'Một ngày có 24 giờ' },
              { id: 'opt-buoi', label: 'Một ngày gồm các buổi: sáng, trưa, chiều, tối' },
              { id: 'opt-10h', label: 'Một ngày chỉ có 10 giờ' },
            ],
            canonicalAnswer: ['opt-24h', 'opt-buoi'],
            points: 15,
          },
          {
            id: createStepId(10, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Khi đồng hồ chỉ 12 giờ trưa, cả kim ngắn và kim dài cùng chỉ vào số 12, đúng hay sai?',
            instruction: 'Hình dung vị trí của hai kim lúc 12 giờ.',
            helper: 'Cả hai kim trùng khít nhau ở đỉnh trên cùng.',
            explanation: 'Đúng, lúc 12 giờ đúng cả kim giờ và phút đều chỉ số 12.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(10, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Một giờ đồng hồ có bao nhiêu phút? (Gõ chữ số)',
            instruction: 'Nhập số phút trong một giờ.',
            helper: 'Kim phút quay một vòng đủ 60 vạch.',
            explanation: 'Một giờ có 60 phút.',
            canonicalAnswer: '60',
            acceptedVariants: ['60 phút', 'sáu mươi'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(10, 1), lessonId: createLessonId(10), stepOrder: 1, stepType: 'question', prompt: 'Chức năng kim ngắn và dài', correctAnswer: 'opt-gio-phut' },
      { id: createStepId(10, 2), lessonId: createLessonId(10), stepOrder: 2, stepType: 'question', prompt: 'Kim ngắn số 7 kim dài số 12', correctAnswer: 'opt-7h' },
      { id: createStepId(10, 3), lessonId: createLessonId(10), stepOrder: 3, stepType: 'question', prompt: 'Nhận định về thời gian trong ngày', correctAnswer: JSON.stringify(['opt-24h', 'opt-buoi']) },
      { id: createStepId(10, 4), lessonId: createLessonId(10), stepOrder: 4, stepType: 'question', prompt: 'Vị trí kim lúc 12 giờ trưa', correctAnswer: 'true' },
      { id: createStepId(10, 5), lessonId: createLessonId(10), stepOrder: 5, stepType: 'question', prompt: 'Số phút trong một giờ', correctAnswer: '60' },
    ],
  },

  // Lesson 26: So sánh lớn hơn, bé hơn và bằng nhau
  {
    lesson: {
      id: createLessonId(26),
      title: 'So sánh lớn hơn, bé hơn và bằng nhau',
      subject: 'Toán học',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'mathematics',
        ageBand: '6-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Làm quen với các dấu >, <, = và so sánh các số trong phạm vi 20',
        description: 'Bé học cách so sánh số lượng đồ vật, sử dụng các dấu so sánh lớn hơn (>), bé hơn (<) và bằng nhau (=) một cách tự tin.',
        image: '/images/lesson-math.png',
        accent: 'ice',
        rating: '5.0',
        steps: [
          {
            id: createStepId(26, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Điền dấu thích hợp vào chỗ chấm: 8 ... 5',
            instruction: 'Chọn dấu so sánh đúng giữa số 8 và số 5.',
            helper: 'Số 8 có nhiều hơn số 5 không nào?',
            explanation: '8 lớn hơn 5, do đó ta điền dấu lớn hơn (>).',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-gt', label: 'Dấu lớn hơn (>)' },
              { id: 'opt-lt', label: 'Dấu bé hơn (<)' },
              { id: 'opt-eq', label: 'Dấu bằng (=)' },
            ],
            canonicalAnswer: 'opt-gt',
            points: 10,
          },
          {
            id: createStepId(26, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp các số sau theo thứ tự từ bé đến lớn: 15, 3, 9, 12',
            instruction: 'Kéo hoặc di chuyển các số từ số nhỏ nhất đến số lớn nhất.',
            helper: 'Số có 1 chữ số nhỏ hơn số có 2 chữ số.',
            explanation: 'Thứ tự từ bé đến lớn là: 3 -> 9 -> 12 -> 15.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'num-3', label: '3' },
              { id: 'num-9', label: '9' },
              { id: 'num-12', label: '12' },
              { id: 'num-15', label: '15' },
            ],
            canonicalAnswer: ['num-3', 'num-9', 'num-12', 'num-15'],
            points: 15,
          },
          {
            id: createStepId(26, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Trong các phép so sánh dưới đây, những phép so sánh nào là đúng?',
            instruction: 'Chọn tất cả các phép so sánh đúng.',
            helper: 'Kiểm tra kỹ từng cặp số nhé.',
            explanation: '7 < 10 và 14 = 14 là các phép so sánh hoàn toàn chính xác.',
            image: '/images/lesson-math.png',
            options: [
              { id: 'opt-7-lt-10', label: '7 < 10' },
              { id: 'opt-14-eq-14', label: '14 = 14' },
              { id: 'opt-18-lt-11', label: '18 < 11' },
            ],
            canonicalAnswer: ['opt-7-lt-10', 'opt-14-eq-14'],
            points: 15,
          },
          {
            id: createStepId(26, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Số 16 bé hơn số 19, đúng hay sai?',
            instruction: 'So sánh hai số có cùng hàng chục là 1, xem hàng đơn vị.',
            helper: 'Hàng đơn vị 6 bé hơn 9.',
            explanation: 'Đúng, 16 bé hơn 19 (16 < 19).',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(26, 5),
            stepOrder: 5,
            questionType: 'fill_blank',
            prompt: 'Số liền sau của số 14 là số nào? (Gõ chữ số)',
            instruction: 'Tìm số lớn hơn 14 đúng 1 đơn vị.',
            helper: '14 thêm 1 bằng mấy?',
            explanation: 'Số liền sau của 14 là 15.',
            canonicalAnswer: '15',
            acceptedVariants: ['mười lăm', 'Số 15'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(26, 1), lessonId: createLessonId(26), stepOrder: 1, stepType: 'question', prompt: 'So sánh 8 và 5', correctAnswer: 'opt-gt' },
      { id: createStepId(26, 2), lessonId: createLessonId(26), stepOrder: 2, stepType: 'question', prompt: 'Sắp xếp số từ bé đến lớn', correctAnswer: JSON.stringify(['num-3', 'num-9', 'num-12', 'num-15']) },
      { id: createStepId(26, 3), lessonId: createLessonId(26), stepOrder: 3, stepType: 'question', prompt: 'Các phép so sánh đúng', correctAnswer: JSON.stringify(['opt-7-lt-10', 'opt-14-eq-14']) },
      { id: createStepId(26, 4), lessonId: createLessonId(26), stepOrder: 4, stepType: 'question', prompt: 'Số 16 bé hơn số 19', correctAnswer: 'true' },
      { id: createStepId(26, 5), lessonId: createLessonId(26), stepOrder: 5, stepType: 'question', prompt: 'Số liền sau số 14', correctAnswer: '15' },
    ],
  },
];
