import type { CatalogLessonEntry } from '../seed-lessons';
import { createLessonId, createStepId } from './literacy';

export const SCIENCE_LESSONS: CatalogLessonEntry[] = [
  // Lesson 21: Bốn mùa tươi đẹp trong năm
  {
    lesson: {
      id: createLessonId(21),
      title: 'Bốn mùa tươi đẹp trong năm',
      subject: 'Khoa học cơ bản',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'basic_science',
        ageBand: '6-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Xuân, hạ, thu, đông và sự thay đổi của thiên nhiên',
        description: 'Khám phá đặc trưng của 4 mùa: hoa đào nở mùa xuân, nắng vàng mùa hè, lá rụng mùa thu và gió lạnh mùa đông.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '5.0',
        steps: [
          {
            id: createStepId(21, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Mùa nào trong năm cây cối đâm chồi nảy lộc và có Tết Nguyên Đán sum vầy?',
            instruction: 'Chọn mùa đầu tiên trong năm.',
            helper: 'Hoa mai, hoa đào nở rộ đón xuân về.',
            explanation: 'Mùa xuân là mùa của Tết cổ truyền và cây cối đâm chồi.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-xuan', label: 'Mùa xuân' },
              { id: 'opt-ha', label: 'Mùa hạ (hè)' },
              { id: 'opt-dong', label: 'Mùa đông' },
            ],
            canonicalAnswer: 'opt-xuan',
            points: 10,
          },
          {
            id: createStepId(21, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp thứ tự 4 mùa luân chuyển trong một năm:',
            instruction: 'Xếp từ mùa bắt đầu năm mới.',
            helper: 'Xuân -> Hạ -> Thu -> Đông.',
            explanation: 'Thứ tự đúng: Mùa xuân -> Mùa hạ -> Mùa thu -> Mùa đông.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'm-xuan', label: 'Mùa xuân' },
              { id: 'm-ha', label: 'Mùa hạ' },
              { id: 'm-thu', label: 'Mùa thu' },
              { id: 'm-dong', label: 'Mùa đông' },
            ],
            canonicalAnswer: ['m-xuan', 'm-ha', 'm-thu', 'm-dong'],
            points: 15,
          },
          {
            id: createStepId(21, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những đặc điểm nào dưới đây là của mùa hè (mùa hạ)?',
            instruction: 'Chọn tất cả các hiện tượng thời tiết mùa hè.',
            helper: 'Nắng chói chang, tiếng ve kêu.',
            explanation: 'Thời tiết nắng nóng, tiếng ve kêu và hoa phượng đỏ rực là nét đặc trưng của mùa hè.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-nang-nong', label: 'Thời tiết nắng vàng, rực rỡ' },
              { id: 'opt-tieng-ve', label: 'Có tiếng ve kêu và hoa phượng đỏ' },
              { id: 'opt-tuyet-roi', label: 'Tuyết rơi phủ trắng xóa khắp nơi' },
            ],
            canonicalAnswer: ['opt-nang-nong', 'opt-tieng-ve'],
            points: 15,
          },
          {
            id: createStepId(21, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Vào mùa đông lạnh giá, chúng ta cần mặc áo ấm, quàng khăn len để giữ ấm cơ thể, đúng hay sai?',
            instruction: 'Xác định cách chăm sóc sức khỏe mùa lạnh.',
            helper: 'Giữ ấm cổ và ngực phòng cảm lạnh.',
            explanation: 'Đúng, giữ ấm cơ thể trong mùa đông giúp tránh bị cảm cúm.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(21, 5),
            stepOrder: 5,
            questionType: 'fill_blank',
            prompt: 'Mùa nào có đêm hội trăng rằm rước đèn ông sao và phá cỗ Trung Thu? (Gõ: mùa thu hoặc thu)',
            instruction: 'Nhập tên mùa có Tết Trung Thu của thiếu nhi.',
            helper: 'Tiết trời mát mẻ tháng Tám âm lịch.',
            explanation: 'Tết Trung Thu diễn ra vào mùa thu.',
            canonicalAnswer: 'mùa thu',
            acceptedVariants: ['thu', 'Mùa thu', 'Thu'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(21, 1), lessonId: createLessonId(21), stepOrder: 1, stepType: 'question', prompt: 'Mùa cây cối đâm chồi nảy lộc', correctAnswer: 'opt-xuan' },
      { id: createStepId(21, 2), lessonId: createLessonId(21), stepOrder: 2, stepType: 'question', prompt: 'Sắp xếp 4 mùa trong năm', correctAnswer: JSON.stringify(['m-xuan', 'm-ha', 'm-thu', 'm-dong']) },
      { id: createStepId(21, 3), lessonId: createLessonId(21), stepOrder: 3, stepType: 'question', prompt: 'Đặc điểm mùa hè', correctAnswer: JSON.stringify(['opt-nang-nong', 'opt-tieng-ve']) },
      { id: createStepId(21, 4), lessonId: createLessonId(21), stepOrder: 4, stepType: 'question', prompt: 'Mặc áo ấm mùa đông', correctAnswer: 'true' },
      { id: createStepId(21, 5), lessonId: createLessonId(21), stepOrder: 5, stepType: 'question', prompt: 'Mùa có Tết Trung Thu', correctAnswer: 'mùa thu' },
    ],
  },

  // Lesson 22: Cây xanh lớn lên như thế nào?
  {
    lesson: {
      id: createLessonId(22),
      title: 'Hạt mầm lớn lên thành cây',
      subject: 'Khoa học cơ bản',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'basic_science',
        ageBand: '6-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Vòng đời phát triển diệu kỳ của thực vật',
        description: 'Quan sát hạt giống nảy mầm, đâm rễ, mọc lá và trổ hoa kết trái qua thời gian.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '4.9',
        steps: [
          {
            id: createStepId(22, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Để hạt mầm nảy mầm và phát triển thành cây tươi tốt, hạt cần những yếu tố thiết yếu nào?',
            instruction: 'Chọn điều kiện sống cơ bản của cây xanh.',
            helper: 'Cây cần uống nước, tắm nắng và đất màu mỡ.',
            explanation: 'Nước, ánh sáng mặt trời, không khí và chất dinh dưỡng trong đất là thiết yếu.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-nuoc-anhsang', label: 'Nước, ánh sáng mặt trời, không khí và đất màu' },
              { id: 'opt-bong-toi', label: 'Chỉ cần để trong tủ tối kín mít' },
              { id: 'opt-khong-nuoc', label: 'Không cần tưới nước bao giờ' },
            ],
            canonicalAnswer: 'opt-nuoc-anhsang',
            points: 10,
          },
          {
            id: createStepId(22, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp các giai đoạn phát triển của cây đậu từ hạt giống:',
            instruction: 'Xếp theo thứ tự từ hạt mầm đến cây có quả.',
            helper: 'Hạt giống -> Nảy mầm -> Cây con -> Ra hoa kết quả.',
            explanation: 'Trình tự: Hạt giống gieo vào đất -> Nảy mầm đâm rễ -> Phát triển cây con -> Ra hoa kết quả.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'g-hat', label: 'Hạt giống được gieo xuống đất ẩm' },
              { id: 'g-mam', label: 'Hạt nảy mầm và nhú rễ con' },
              { id: 'g-caycon', label: 'Cây con mọc lá xanh đón nắng' },
              { id: 'g-rahoa', label: 'Cây trưởng thành ra hoa kết quả' },
            ],
            canonicalAnswer: ['g-hat', 'g-mam', 'g-caycon', 'g-rahoa'],
            points: 15,
          },
          {
            id: createStepId(22, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Bộ phận nào của cây làm nhiệm vụ hút nước và chất dinh dưỡng từ lòng đất?',
            instruction: 'Chọn bộ phận cắm sâu dưới đất.',
            helper: 'Bộ phận nằm ẩn dưới mặt đất giữ cho cây đứng vững.',
            explanation: 'Rễ cây cắm sâu hút nước và khoáng chất nuôi toàn bộ cây.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-re-cay', label: 'Rễ cây' },
              { id: 'opt-than-cay', label: 'Thân cây' },
              { id: 'opt-bong-hoa', label: 'Bông hoa' },
            ],
            canonicalAnswer: ['opt-re-cay'],
            points: 15,
          },
          {
            id: createStepId(22, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Lá cây xanh có chất diệp lục giúp cây quang hợp và tạo ra khí oxy trong lành cho con người hít thở, đúng hay sai?',
            instruction: 'Vai trò của lá cây xanh với môi trường.',
            helper: 'Cây xanh được ví như lá phổi xanh của Trái Đất.',
            explanation: 'Đúng, cây xanh quang hợp hấp thụ CO2 và thải ra khí O2 cho sự sống.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(22, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Bộ phận nào của cây thường có màu xanh lục và hứng ánh sáng mặt trời? (Gõ tên bộ phận)',
            instruction: 'Nhập tên bộ phận hứng nắng của cây.',
            helper: 'Lá cây.',
            explanation: 'Lá cây là nơi diễn ra quá trình quang hợp chính.',
            canonicalAnswer: 'lá cây',
            acceptedVariants: ['lá', 'la cay', 'la', 'Lá cây'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(22, 1), lessonId: createLessonId(22), stepOrder: 1, stepType: 'question', prompt: 'Yếu tố cây cần để sống', correctAnswer: 'opt-nuoc-anhsang' },
      { id: createStepId(22, 2), lessonId: createLessonId(22), stepOrder: 2, stepType: 'question', prompt: 'Vòng đời của cây', correctAnswer: JSON.stringify(['g-hat', 'g-mam', 'g-caycon', 'g-rahoa']) },
      { id: createStepId(22, 3), lessonId: createLessonId(22), stepOrder: 3, stepType: 'question', prompt: 'Bộ phận hút nước từ đất', correctAnswer: JSON.stringify(['opt-re-cay']) },
      { id: createStepId(22, 4), lessonId: createLessonId(22), stepOrder: 4, stepType: 'question', prompt: 'Lá cây quang hợp tạo oxy', correctAnswer: 'true' },
      { id: createStepId(22, 5), lessonId: createLessonId(22), stepOrder: 5, stepType: 'question', prompt: 'Bộ phận màu xanh hứng nắng', correctAnswer: 'lá cây' },
    ],
  },

  // Lesson 23: Vòng tuần hoàn của giọt nước tí hon
  {
    lesson: {
      id: createLessonId(23),
      title: 'Vòng tuần hoàn của giọt nước',
      subject: 'Khoa học cơ bản',
      gradeLevel: 'Lớp 1 - 3',
      estimatedMinutes: 14,
      isPublished: true,
      content: JSON.stringify({
        track: 'basic_science',
        ageBand: '6-9 tuổi',
        difficulty: 'Trung bình',
        subtitle: 'Hơi nước, đám mây và cơn mưa mát lành',
        description: 'Khám phá hành trình phiêu lưu của giọt nước bốc hơi thành mây rồi đổ mưa trở về mặt đất.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '4.9',
        steps: [
          {
            id: createStepId(23, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Dưới ánh nắng mặt trời ấm áp, nước ở ao hồ, sông biển biến thành gì bay lên bầu trời?',
            instruction: 'Hiện tượng bốc hơi của nước.',
            helper: 'Nước bốc thành hơi nước nhẹ nhàng.',
            explanation: 'Nước hấp thụ nhiệt bốc hơi thành hơi nước bay lên cao.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-hoi-nuoc', label: 'Bốc hơi thành hơi nước bay lên cao' },
              { id: 'opt-hoa-da', label: 'Đóng thành những tảng đá cứng' },
              { id: 'opt-bien-mat', label: 'Biến mất vĩnh viễn' },
            ],
            canonicalAnswer: 'opt-hoi-nuoc',
            points: 10,
          },
          {
            id: createStepId(23, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp hành trình của một giọt nước theo vòng tuần hoàn:',
            instruction: 'Xếp các bước từ bốc hơi đến rơi thành mưa.',
            helper: 'Bốc hơi -> Hóa mây -> Mưa rơi -> Chảy về biển.',
            explanation: 'Trình tự: Nước biển bốc hơi -> Ngưng tụ thành mây -> Trĩu nặng rơi thành mưa -> Nước mưa chảy về nguồn.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'c-bochoi', label: 'Nước biển được sưởi ấm và bốc hơi lên cao' },
              { id: 'c-ngungtu', label: 'Hơi nước gặp lạnh ngưng tụ thành những đám mây' },
              { id: 'c-muaroi', label: 'Các giọt nước nặng trĩu rơi xuống đất thành mưa' },
              { id: 'c-chayve', label: 'Nước mưa ngấm vào đất, chảy ra sông suối về biển' },
            ],
            canonicalAnswer: ['c-bochoi', 'c-ngungtu', 'c-muaroi', 'c-chayve'],
            points: 15,
          },
          {
            id: createStepId(23, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Nước có thể tồn tại ở những trạng thái vật lý nào trong tự nhiên?',
            instruction: 'Chọn các thể của nước.',
            helper: 'Nước đá, nước uống và hơi nước.',
            explanation: 'Nước tồn tại ở thể lỏng (nước), thể rắn (băng/đá) và thể khí (hơi nước).',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-the-long', label: 'Thể lỏng (nước suối, nước uống)' },
              { id: 'opt-the-ran', label: 'Thể rắn (nước đá, tuyết, băng)' },
              { id: 'opt-the-khi', label: 'Thể khí (hơi nước)' },
            ],
            canonicalAnswer: ['opt-the-long', 'opt-the-ran', 'opt-the-khi'],
            points: 15,
          },
          {
            id: createStepId(23, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Nước sạch là tài nguyên vô giá, chúng ta cần tiết kiệm và không làm ô nhiễm nguồn nước, đúng hay sai?',
            instruction: 'Ý thức bảo vệ môi trường nước.',
            helper: 'Mọi sinh vật đều cần nước sạch để tồn tại.',
            explanation: 'Đúng, bảo vệ nguồn nước sạch là bảo vệ sự sống trên Trái Đất.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(23, 5),
            stepOrder: 5,
            questionType: 'fill_blank',
            prompt: 'Khi hơi nước ngưng tụ trên cao thành từng khối bồng bềnh màu trắng, đó gọi là đám ...',
            instruction: 'Gõ từ chỉ đám mây trên bầu trời.',
            helper: 'Đám mây.',
            explanation: 'Hơi nước ngưng tụ tạo thành đám mây.',
            canonicalAnswer: 'mây',
            acceptedVariants: ['đám mây', 'may', 'Mây'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(23, 1), lessonId: createLessonId(23), stepOrder: 1, stepType: 'question', prompt: 'Nước bốc hơi thành gì', correctAnswer: 'opt-hoi-nuoc' },
      { id: createStepId(23, 2), lessonId: createLessonId(23), stepOrder: 2, stepType: 'question', prompt: 'Sắp xếp vòng tuần hoàn nước', correctAnswer: JSON.stringify(['c-bochoi', 'c-ngungtu', 'c-muaroi', 'c-chayve']) },
      { id: createStepId(23, 3), lessonId: createLessonId(23), stepOrder: 3, stepType: 'question', prompt: 'Ba trạng thái của nước', correctAnswer: JSON.stringify(['opt-the-long', 'opt-the-ran', 'opt-the-khi']) },
      { id: createStepId(23, 4), lessonId: createLessonId(23), stepOrder: 4, stepType: 'question', prompt: 'Tiết kiệm nước sạch', correctAnswer: 'true' },
      { id: createStepId(23, 5), lessonId: createLessonId(23), stepOrder: 5, stepType: 'question', prompt: 'Khối bồng bềnh là đám mây', correctAnswer: 'mây' },
    ],
  },

  // Lesson 24: Mặt Trời, Mặt Trăng và các vì sao
  {
    lesson: {
      id: createLessonId(24),
      title: 'Mặt Trời, Mặt Trăng và bầu trời đêm',
      subject: 'Khoa học cơ bản',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'basic_science',
        ageBand: '6-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Ngày và đêm, ánh sáng và bóng tối',
        description: 'Tìm hiểu nguồn ánh sáng ấm áp của Mặt Trời ban ngày và vẻ đẹp dịu dàng của Mặt Trăng ban đêm.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '5.0',
        steps: [
          {
            id: createStepId(24, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Thiên thể nào chiếu sáng rực rỡ và sưởi ấm cho Trái Đất vào ban ngày?',
            instruction: 'Chọn ngôi sao sáng nhất của hệ mặt trời.',
            helper: 'Mặt Trời mọc ở hướng Đông.',
            explanation: 'Mặt Trời cung cấp ánh sáng và hơi ấm cho ban ngày trên Trái Đất.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-mattroi', label: 'Mặt Trời' },
              { id: 'opt-mattrang', label: 'Mặt Trăng' },
              { id: 'opt-saobang', label: 'Sao băng' },
            ],
            canonicalAnswer: 'opt-mattroi',
            points: 10,
          },
          {
            id: createStepId(24, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Mặt Trời thường mọc ở hướng nào vào buổi sáng sớm?',
            instruction: 'Xác định phương hướng mọc của Mặt Trời.',
            helper: 'Mặt Trời mọc đằng Đông, lặn đằng Tây.',
            explanation: 'Mặt Trời mọc ở hướng Đông và lặn ở hướng Tây.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-dong', label: 'Hướng Đông' },
              { id: 'opt-tay', label: 'Hướng Tây' },
              { id: 'opt-bac', label: 'Hướng Bắc' },
            ],
            canonicalAnswer: 'opt-dong',
            points: 10,
          },
          {
            id: createStepId(24, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những thiên thể hoặc hiện tượng nào em có thể nhìn thấy trên bầu trời vào ban đêm quang đãng?',
            instruction: 'Chọn các hình ảnh của bầu trời đêm.',
            helper: 'Ánh trăng và các vì sao lấp lánh.',
            explanation: 'Mặt Trăng và muôn ngàn vì sao sáng lấp lánh hiện lên trên bầu trời đêm.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-trang', label: 'Mặt Trăng dịu hiền' },
              { id: 'opt-sao', label: 'Những vì sao lấp lánh' },
              { id: 'opt-cau-vong', label: 'Cầu vồng rực rỡ giữa trời nắng' },
            ],
            canonicalAnswer: ['opt-trang', 'opt-sao'],
            points: 15,
          },
          {
            id: createStepId(24, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Hình dạng của Mặt Trăng có thể thay đổi trong tháng từ trăng khuyết hình lưỡi liềm đến trăng tròn xoe, đúng hay sai?',
            instruction: 'Hiện tượng các pha của Mặt Trăng.',
            helper: 'Đầu tháng trăng khuyết, rằm trăng tròn.',
            explanation: 'Đúng, Mặt Trăng tròn khuyết tùy theo vị trí tương đối với Mặt Trời và Trái Đất.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(24, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Hành tinh xanh tươi nơi con người và muôn loài đang cùng chung sống có tên là gì? (Gõ tên hành tinh)',
            instruction: 'Nhập tên hành tinh của chúng ta.',
            helper: 'Trái Đất.',
            explanation: 'Chúng ta đang sinh sống trên Trái Đất xinh đẹp.',
            canonicalAnswer: 'trái đất',
            acceptedVariants: ['Trái Đất', 'trai dat', 'Trái đất'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(24, 1), lessonId: createLessonId(24), stepOrder: 1, stepType: 'question', prompt: 'Thiên thể chiếu sáng ban ngày', correctAnswer: 'opt-mattroi' },
      { id: createStepId(24, 2), lessonId: createLessonId(24), stepOrder: 2, stepType: 'question', prompt: 'Mặt Trời mọc hướng Đông', correctAnswer: 'opt-dong' },
      { id: createStepId(24, 3), lessonId: createLessonId(24), stepOrder: 3, stepType: 'question', prompt: 'Hiện tượng trên bầu trời đêm', correctAnswer: JSON.stringify(['opt-trang', 'opt-sao']) },
      { id: createStepId(24, 4), lessonId: createLessonId(24), stepOrder: 4, stepType: 'question', prompt: 'Trăng khuyết và trăng tròn', correctAnswer: 'true' },
      { id: createStepId(24, 5), lessonId: createLessonId(24), stepOrder: 5, stepType: 'question', prompt: 'Tên hành tinh chúng ta sống', correctAnswer: 'trái đất' },
    ],
  },
];
