import type { CatalogLessonEntry } from '../seed-lessons';
import { createLessonId, createStepId } from './literacy';

export const SOCIAL_SAFETY_LESSONS: CatalogLessonEntry[] = [
  // Lesson 16: Nhận diện và gọi tên cảm xúc
  {
    lesson: {
      id: createLessonId(16),
      title: 'Nhận diện và gọi tên cảm xúc',
      subject: 'Cảm xúc & An toàn',
      gradeLevel: 'Mầm non - Lớp 1',
      estimatedMinutes: 10,
      isPublished: true,
      content: JSON.stringify({
        track: 'social_emotional_safety',
        ageBand: '5-7 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Vui vẻ, buồn bã, tức giận, sợ hãi',
        description: 'Học cách hiểu cảm xúc trong lòng mình và chia sẻ cùng người thân một cách an toàn.',
        image: '/images/lesson-social.png',
        accent: 'pink',
        rating: '5.0',
        steps: [
          {
            id: createStepId(16, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Khi được bố mẹ khen ngợi hoặc cùng bạn chơi vui, bé thường cảm thấy thế nào?',
            instruction: 'Chọn cảm xúc tích cực, ấm áp.',
            helper: 'Miệng bé nở nụ cười tươi.',
            explanation: 'Đó là cảm xúc vui vẻ, hạnh phúc.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-vui', label: 'Vui vẻ, hạnh phúc' },
              { id: 'opt-gian', label: 'Tức giận' },
              { id: 'opt-so', label: 'Sợ hãi' },
            ],
            canonicalAnswer: 'opt-vui',
            points: 10,
          },
          {
            id: createStepId(16, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Khi cảm thấy tức giận, việc làm nào dưới đây giúp bé bình tĩnh lại một cách an toàn?',
            instruction: 'Chọn hành vi điều hòa cảm xúc đúng đắn.',
            helper: 'Hít vào thật sâu rồi thở ra từ từ.',
            explanation: 'Hít thở sâu 3 lần giúp cơ thể và tâm trí bình tĩnh trở lại.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-hittho', label: 'Hít thở sâu chậm rãi 3 lần' },
              { id: 'opt-danhban', label: 'La hét và đánh bạn' },
              { id: 'opt-nemdo', label: 'Ném đồ đạc xuống sàn' },
            ],
            canonicalAnswer: 'opt-hittho',
            points: 10,
          },
          {
            id: createStepId(16, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những cảm xúc nào dưới đây là cảm xúc hoàn toàn tự nhiên mà ai cũng có lúc trải qua?',
            instruction: 'Chọn tất cả các cảm xúc tự nhiên của con người.',
            helper: 'Mỗi cảm xúc đều mang một thông điệp riêng.',
            explanation: 'Vui vẻ, buồn bã và lo lắng đều là những cảm xúc bình thường của con người.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-buon', label: 'Buồn bã khi mất đồ chơi' },
              { id: 'opt-lo', label: 'Hồi hộp, lo lắng trước việc mới' },
              { id: 'opt-vui-ve', label: 'Hân hoan khi làm được việc tốt' },
            ],
            canonicalAnswer: ['opt-buon', 'opt-lo', 'opt-vui-ve'],
            points: 15,
          },
          {
            id: createStepId(16, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Khóc khi cảm thấy buồn không phải là xấu hổ, bé có thể tâm sự với cha mẹ để nhẹ lòng hơn, đúng hay sai?',
            instruction: 'Xác định nhận thức lành mạnh về cảm xúc buồn.',
            helper: 'Nước mắt giúp giải tỏa bớt nỗi buồn trong lòng.',
            explanation: 'Đúng, chia sẻ cảm xúc với người thân luôn là điều an toàn và lành mạnh.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(16, 5),
            stepOrder: 5,
            questionType: 'fill_blank',
            prompt: 'Điền từ thích hợp: Khi gặp chuyện buồn, em nên tìm ... để được ôm ấp và an ủi.',
            instruction: 'Gõ người thân yêu thương bé nhất.',
            helper: 'Bố mẹ, người thân.',
            explanation: 'Cha mẹ là chỗ dựa bình yên nhất của bé.',
            canonicalAnswer: 'bố mẹ',
            acceptedVariants: ['cha mẹ', 'mẹ', 'ba mẹ', 'bo me'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(16, 1), lessonId: createLessonId(16), stepOrder: 1, stepType: 'question', prompt: 'Cảm xúc khi được khen', correctAnswer: 'opt-vui' },
      { id: createStepId(16, 2), lessonId: createLessonId(16), stepOrder: 2, stepType: 'question', prompt: 'Hành động khi tức giận', correctAnswer: 'opt-hittho' },
      { id: createStepId(16, 3), lessonId: createLessonId(16), stepOrder: 3, stepType: 'question', prompt: 'Cảm xúc tự nhiên của con người', correctAnswer: JSON.stringify(['opt-buon', 'opt-lo', 'opt-vui-ve']) },
      { id: createStepId(16, 4), lessonId: createLessonId(16), stepOrder: 4, stepType: 'question', prompt: 'Khóc khi buồn không xấu hổ', correctAnswer: 'true' },
      { id: createStepId(16, 5), lessonId: createLessonId(16), stepOrder: 5, stepType: 'question', prompt: 'Tìm ai khi buồn', correctAnswer: 'bố mẹ' },
    ],
  },

  // Lesson 17: Quy tắc 5 ngón tay: Bảo vệ cơ thể em
  {
    lesson: {
      id: createLessonId(17),
      title: 'Quy tắc 5 ngón tay bảo vệ cơ thể',
      subject: 'Cảm xúc & An toàn',
      gradeLevel: 'Mầm non - Lớp 2',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'social_emotional_safety',
        ageBand: '5-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'An toàn thân thể và phòng chống xâm hại',
        description: 'Bé ghi nhớ ranh giới tiếp xúc an toàn theo quy tắc 5 ngón tay thân thuộc.',
        image: '/images/lesson-social.png',
        accent: 'pink',
        rating: '5.0',
        steps: [
          {
            id: createStepId(17, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Ngón cái (ngón gần bé nhất) tượng trưng cho ai được phép ôm hôn thân mật?',
            instruction: 'Xác định nhóm người thân ruột thịt.',
            helper: 'Ông bà, cha mẹ, anh chị em ruột.',
            explanation: 'Ngón cái là người thân ruột thịt trong gia đình.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-ruot-thit', label: 'Bố mẹ, ông bà, anh chị em ruột' },
              { id: 'opt-nguoi-la', label: 'Người lạ mới gặp ngoài đường' },
              { id: 'opt-bac-hangxom', label: 'Bất kỳ người lớn nào' },
            ],
            canonicalAnswer: 'opt-ruot-thit',
            points: 10,
          },
          {
            id: createStepId(17, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Ngón út (ngón xa nhất) nhắc nhở bé điều gì đối với người hoàn toàn xa lạ?',
            instruction: 'Quy tắc ứng xử với người lạ.',
            helper: 'Không cho đụng chạm, xua tay từ chối và giữ khoảng cách.',
            explanation: 'Ngón út tượng trưng cho việc giữ khoảng cách an toàn, xua tay từ chối người lạ.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-xuatai', label: 'Xua tay, giữ khoảng cách và không cho chạm vào người' },
              { id: 'opt-omhon', label: 'Chạy lại ôm hôn người lạ' },
              { id: 'opt-chodi', label: 'Đi theo họ đến chỗ vắng' },
            ],
            canonicalAnswer: 'opt-xuatai',
            points: 10,
          },
          {
            id: createStepId(17, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những vùng nào trên cơ thể là vùng riêng tư tuyệt đối (vùng đồ bơi) không ai được tùy tiện nhìn hoặc chạm vào?',
            instruction: 'Chọn các vùng riêng tư được đồ bơi che chắn.',
            helper: 'Quy tắc đồ bơi bảo vệ thân thể.',
            explanation: 'Vùng ngực, giữa hai đùi và mông là vùng đồ bơi riêng tư của bé.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-nguc', label: 'Vùng ngực' },
              { id: 'opt-giua-dui', label: 'Vùng giữa hai đùi và mông' },
              { id: 'opt-ban-tay', label: 'Bàn tay' },
            ],
            canonicalAnswer: ['opt-nguc', 'opt-giua-dui'],
            points: 15,
          },
          {
            id: createStepId(17, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Bác sĩ chỉ được khám vùng riêng tư khi có sự đồng ý và có mặt của cha mẹ, đúng hay sai?',
            instruction: 'Xác định quy tắc an toàn y tế.',
            helper: 'Luôn phải có cha mẹ bên cạnh bảo vệ.',
            explanation: 'Đúng, bác sĩ chỉ thăm khám khi cần thiết và bắt buộc phải có cha mẹ đi cùng.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(17, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Khi ai đó cố tình chạm vào vùng riêng tư khiến bé khó chịu, bé phải hét to từ gì? (Gõ 1 từ: KHÔNG hoặc DỪNG LẠI)',
            instruction: 'Nhập tiếng hô dứt khoát để từ chối.',
            helper: 'Hô to chữ KHÔNG!',
            explanation: 'Bé hét to "KHÔNG!" hoặc "DỪNG LẠI!" và chạy ngay đến chỗ cha mẹ.',
            canonicalAnswer: 'không',
            acceptedVariants: ['Không', 'KHÔNG', 'dừng lại', 'Dừng lại'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(17, 1), lessonId: createLessonId(17), stepOrder: 1, stepType: 'question', prompt: 'Ngón cái ôm hôn', correctAnswer: 'opt-ruot-thit' },
      { id: createStepId(17, 2), lessonId: createLessonId(17), stepOrder: 2, stepType: 'question', prompt: 'Ngón út với người lạ', correctAnswer: 'opt-xuatai' },
      { id: createStepId(17, 3), lessonId: createLessonId(17), stepOrder: 3, stepType: 'question', prompt: 'Vùng riêng tư đồ bơi', correctAnswer: JSON.stringify(['opt-nguc', 'opt-giua-dui']) },
      { id: createStepId(17, 4), lessonId: createLessonId(17), stepOrder: 4, stepType: 'question', prompt: 'Quy tắc khám bệnh của bác sĩ', correctAnswer: 'true' },
      { id: createStepId(17, 5), lessonId: createLessonId(17), stepOrder: 5, stepType: 'question', prompt: 'Hét to từ chối', correctAnswer: 'không' },
    ],
  },

  // Lesson 18: Lạc đường nơi đông người: Bé cần làm gì?
  {
    lesson: {
      id: createLessonId(18),
      title: 'Bé cần làm gì khi bị lạc?',
      subject: 'Cảm xúc & An toàn',
      gradeLevel: 'Mầm non - Lớp 2',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'social_emotional_safety',
        ageBand: '5-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Kỹ năng thoát hiểm và tìm người giúp đỡ',
        description: 'Biết cách đứng yên một chỗ, tìm chú công an hoặc nhân viên siêu thị khi bị lạc cha mẹ.',
        image: '/images/lesson-social.png',
        accent: 'pink',
        rating: '4.9',
        steps: [
          {
            id: createStepId(18, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Ngay khi nhận ra mình bị lạc mất cha mẹ ở siêu thị, bé nên làm gì đầu tiên?',
            instruction: 'Chọn phản ứng bình tĩnh và an toàn.',
            helper: 'Đừng chạy lung tung khiến cha mẹ khó tìm.',
            explanation: 'Bé nên đứng yên tại chỗ và quan sát xung quanh.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-dungyen', label: 'Đứng yên tại chỗ, không chạy lung tung' },
              { id: 'opt-chay-ra-duong', label: 'Chạy một mình ra ngoài đường lớn' },
              { id: 'opt-di-theo-la', label: 'Đi theo bất kỳ ai bảo đi cùng' },
            ],
            canonicalAnswer: 'opt-dungyen',
            points: 10,
          },
          {
            id: createStepId(18, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Những người mặc đồng phục nào bé có thể tin tưởng nhờ giúp đỡ gọi điện cho cha mẹ?',
            instruction: 'Tìm người hỗ trợ đáng tin cậy.',
            helper: 'Chú công an, chú bảo vệ, cô thu ngân siêu thị.',
            explanation: 'Chú công an hoặc nhân viên bảo vệ, thu ngân có đeo bảng tên là người an toàn.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-congan', label: 'Chú công an, chú bảo vệ hoặc cô thu ngân siêu thị' },
              { id: 'opt-nguoi-bit-mat', label: 'Người lạ mặt bịt kín khẩu trang rủ đi chỗ vắng' },
              { id: 'opt-khong-ai', label: 'Không tin tưởng bất kỳ ai' },
            ],
            canonicalAnswer: 'opt-congan',
            points: 10,
          },
          {
            id: createStepId(18, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những thông tin quan trọng nào bé cần học thuộc lòng để tìm lại người thân?',
            instruction: 'Chọn các thông tin liên lạc cần nhớ.',
            helper: 'Số điện thoại và họ tên.',
            explanation: 'Họ tên và số điện thoại của cha mẹ là hai thông tin quan trọng nhất.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-sdt', label: 'Số điện thoại của bố hoặc mẹ' },
              { id: 'opt-ten-bome', label: 'Họ và tên của bố mẹ' },
              { id: 'opt-ten-game', label: 'Tên nhân vật trong trò chơi điện tử' },
            ],
            canonicalAnswer: ['opt-sdt', 'opt-ten-bome'],
            points: 15,
          },
          {
            id: createStepId(18, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Khi ở nơi đông người, bé luôn phải nắm tay cha mẹ và không tự ý rời xa, đúng hay sai?',
            instruction: 'Quy tắc phòng ngừa bị lạc.',
            helper: 'Luôn đi cạnh người lớn.',
            explanation: 'Đúng, luôn nắm tay người lớn là cách tốt nhất tránh bị lạc.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(18, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Số điện thoại khẩn cấp của Cảnh sát Công an tại Việt Nam là gì? (Gõ 3 chữ số)',
            instruction: 'Nhập số tổng đài khẩn cấp công an.',
            helper: 'Một - một - ba.',
            explanation: 'Số điện thoại khẩn cấp của công an là 113.',
            canonicalAnswer: '113',
            acceptedVariants: ['một một ba', '113.'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(18, 1), lessonId: createLessonId(18), stepOrder: 1, stepType: 'question', prompt: 'Hành động đầu tiên khi bị lạc', correctAnswer: 'opt-dungyen' },
      { id: createStepId(18, 2), lessonId: createLessonId(18), stepOrder: 2, stepType: 'question', prompt: 'Người tin tưởng nhờ giúp đỡ', correctAnswer: 'opt-congan' },
      { id: createStepId(18, 3), lessonId: createLessonId(18), stepOrder: 3, stepType: 'question', prompt: 'Thông tin bé cần học thuộc', correctAnswer: JSON.stringify(['opt-sdt', 'opt-ten-bome']) },
      { id: createStepId(18, 4), lessonId: createLessonId(18), stepOrder: 4, stepType: 'question', prompt: 'Nắm tay cha mẹ nơi đông người', correctAnswer: 'true' },
      { id: createStepId(18, 5), lessonId: createLessonId(18), stepOrder: 5, stepType: 'question', prompt: 'Số điện thoại công an 113', correctAnswer: '113' },
    ],
  },

  // Lesson 19: An toàn giao thông khi đi bộ
  {
    lesson: {
      id: createLessonId(19),
      title: 'Bé đi bộ an toàn trên đường',
      subject: 'Cảm xúc & An toàn',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'social_emotional_safety',
        ageBand: '6-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Đèn tín hiệu và vạch kẻ đường cho người đi bộ',
        description: 'Học cách nhận biết tín hiệu đèn giao thông và đi bộ đúng phần đường quy định.',
        image: '/images/lesson-social.png',
        accent: 'pink',
        rating: '4.8',
        steps: [
          {
            id: createStepId(19, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Đèn tín hiệu giao thông màu gì báo hiệu người và phương tiện phải dừng lại?',
            instruction: 'Chọn màu sắc đèn dừng lại.',
            helper: 'Màu đỏ báo dừng, màu xanh được đi.',
            explanation: 'Đèn đỏ có hiệu lệnh dừng lại.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-do', label: 'Đèn màu đỏ' },
              { id: 'opt-xanh', label: 'Đèn màu xanh' },
              { id: 'opt-vang', label: 'Đèn màu vàng' },
            ],
            canonicalAnswer: 'opt-do',
            points: 10,
          },
          {
            id: createStepId(19, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Người đi bộ muốn qua đường cần đi ở vị trí nào an toàn nhất?',
            instruction: 'Tìm vạch kẻ đường dành cho người đi bộ.',
            helper: 'Vạch sơn trắng hình sọc ngựa vằn.',
            explanation: 'Người đi bộ phải qua đường trên vạch kẻ trắng dành riêng cho người đi bộ.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-vach-ke', label: 'Đi trên vạch sơn trắng dành cho người đi bộ' },
              { id: 'opt-chay-cat-mat', label: 'Chạy tạt ngang đầu xe ô tô đang chạy' },
              { id: 'opt-treo-raobang', label: 'Trèo qua dải phân cách giữa đường' },
            ],
            canonicalAnswer: 'opt-vach-ke',
            points: 10,
          },
          {
            id: createStepId(19, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những hành vi nào dưới đây là nguy hiểm khi đang đi trên vỉa hè hoặc đường phố?',
            instruction: 'Chọn các hành động không an toàn cần tránh.',
            helper: 'Không chơi đùa dưới lòng đường.',
            explanation: 'Đá bóng dưới lòng đường và vừa đi vừa xem điện thoại là rất nguy hiểm.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-da-bong', label: 'Đá bóng, đuổi bắt dưới lòng đường' },
              { id: 'opt-xem-dt', label: 'Vừa đi vừa cắm cúi xem điện thoại' },
              { id: 'opt-quan-sat', label: 'Quan sát cẩn thận xe cộ trước khi qua đường' },
            ],
            canonicalAnswer: ['opt-da-bong', 'opt-xem-dt'],
            points: 15,
          },
          {
            id: createStepId(19, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Trẻ em khi đi bộ qua đường lớn cần có người lớn dắt tay để đảm bảo an toàn, đúng hay sai?',
            instruction: 'Xác định quy tắc bảo vệ trẻ nhỏ khi tham gia giao thông.',
            helper: 'Người lớn có tầm quan sát tốt hơn và phản xạ nhanh.',
            explanation: 'Đúng, trẻ nhỏ luôn cần người lớn nắm tay dẫn qua đường.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(19, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Đèn tín hiệu giao thông màu gì cho phép bé được qua đường an toàn? (Gõ tên màu)',
            instruction: 'Nhập màu sắc của đèn được phép đi.',
            helper: 'Màu của lá cây.',
            explanation: 'Đèn xanh cho phép người đi bộ qua đường.',
            canonicalAnswer: 'xanh',
            acceptedVariants: ['màu xanh', 'xanh lá', 'Xanh'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(19, 1), lessonId: createLessonId(19), stepOrder: 1, stepType: 'question', prompt: 'Đèn báo dừng lại', correctAnswer: 'opt-do' },
      { id: createStepId(19, 2), lessonId: createLessonId(19), stepOrder: 2, stepType: 'question', prompt: 'Vị trí qua đường an toàn', correctAnswer: 'opt-vach-ke' },
      { id: createStepId(19, 3), lessonId: createLessonId(19), stepOrder: 3, stepType: 'question', prompt: 'Hành vi nguy hiểm trên đường', correctAnswer: JSON.stringify(['opt-da-bong', 'opt-xem-dt']) },
      { id: createStepId(19, 4), lessonId: createLessonId(19), stepOrder: 4, stepType: 'question', prompt: 'Người lớn dắt tay qua đường', correctAnswer: 'true' },
      { id: createStepId(19, 5), lessonId: createLessonId(19), stepOrder: 5, stepType: 'question', prompt: 'Màu đèn được phép đi', correctAnswer: 'xanh' },
    ],
  },

  // Lesson 20: Bạn tốt quanh em: Lịch sự và chia sẻ
  {
    lesson: {
      id: createLessonId(20),
      title: 'Bạn tốt quanh em: Lịch sự và chia sẻ',
      subject: 'Cảm xúc & An toàn',
      gradeLevel: 'Mầm non - Lớp 2',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'social_emotional_safety',
        ageBand: '5-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Lời cảm ơn, xin lỗi và biết nhường nhịn',
        description: 'Xây dựng tình bạn trong sáng, biết dùng lời hay ý đẹp và chơi hòa đồng cùng các bạn.',
        image: '/images/lesson-social.png',
        accent: 'pink',
        rating: '4.9',
        steps: [
          {
            id: createStepId(20, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Khi vô tình va phải bạn làm bạn làm rơi hộp bút, bé nên nói câu gì đầu tiên?',
            instruction: 'Chọn lời nói lịch sự và chân thành.',
            helper: 'Lời nhận lỗi khi làm phiền người khác.',
            explanation: 'Bé nên nói "Mình xin lỗi bạn" và nhặt bút giúp bạn.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-xinloi', label: 'Mình xin lỗi bạn, để mình nhặt giúp bạn nhé!' },
              { id: 'opt-cuoi', label: 'Bỏ chạy và cười to' },
              { id: 'opt-do-loi', label: 'Đổ lỗi là do bạn đi đứng không cẩn thận' },
            ],
            canonicalAnswer: 'opt-xinloi',
            points: 10,
          },
          {
            id: createStepId(20, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Khi được bạn chia sẻ cho mượn đồ chơi, bé nên nói câu gì?',
            instruction: 'Chọn câu cảm ơn lịch thiệp.',
            helper: 'Thể hiện lòng biết ơn.',
            explanation: 'Bé nói lời "Cảm ơn bạn nhé!".',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-camon', label: 'Cảm ơn bạn rất nhiều!' },
              { id: 'opt-imlang', label: 'Cầm lấy và im lặng không nói gì' },
              { id: 'opt-che', label: 'Chê đồ chơi của bạn cũ kỹ' },
            ],
            canonicalAnswer: 'opt-camon',
            points: 10,
          },
          {
            id: createStepId(20, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Một người bạn tốt thường có những hành động nào?',
            instruction: 'Chọn tất cả những việc làm của một người bạn đáng mến.',
            helper: 'Biết chia sẻ và tôn trọng bạn bè.',
            explanation: 'Biết nhường đồ chơi và an ủi khi bạn buồn là biểu hiện của bạn tốt.',
            image: '/images/lesson-social.png',
            options: [
              { id: 'opt-nhuong-do', label: 'Biết chia sẻ đồ chơi và nhường nhịn' },
              { id: 'opt-an-ui', label: 'Động viên, an ủi khi bạn gặp khó khăn' },
              { id: 'opt-noi-xau', label: 'Nói xấu và giấu đồ của bạn' },
            ],
            canonicalAnswer: ['opt-nhuong-do', 'opt-an-ui'],
            points: 15,
          },
          {
            id: createStepId(20, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Luôn biết lắng nghe và tôn trọng ý kiến của bạn bè giúp tình bạn thêm gắn kết, đúng hay sai?',
            instruction: 'Xác định giá trị của sự tôn trọng trong tình bạn.',
            helper: 'Ai cũng muốn được lắng nghe.',
            explanation: 'Đúng, lắng nghe và tôn trọng là nền tảng của tình bạn đẹp.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(20, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Cùng với lời "Xin lỗi", câu thần chú lịch sự nào thường được nói khi nhận quà? (Gõ 2 từ: Cảm ơn)',
            instruction: 'Nhập lời nói bày tỏ sự cảm kích.',
            helper: 'C-ả-m  ơ-n.',
            explanation: 'Lời cảm ơn là nét đẹp văn hóa trong giao tiếp.',
            canonicalAnswer: 'cảm ơn',
            acceptedVariants: ['Cảm ơn', 'cam on', 'Cam on'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(20, 1), lessonId: createLessonId(20), stepOrder: 1, stepType: 'question', prompt: 'Lời nói khi va phải bạn', correctAnswer: 'opt-xinloi' },
      { id: createStepId(20, 2), lessonId: createLessonId(20), stepOrder: 2, stepType: 'question', prompt: 'Lời nói khi được mượn đồ', correctAnswer: 'opt-camon' },
      { id: createStepId(20, 3), lessonId: createLessonId(20), stepOrder: 3, stepType: 'question', prompt: 'Hành động của người bạn tốt', correctAnswer: JSON.stringify(['opt-nhuong-do', 'opt-an-ui']) },
      { id: createStepId(20, 4), lessonId: createLessonId(20), stepOrder: 4, stepType: 'question', prompt: 'Lắng nghe bạn bè', correctAnswer: 'true' },
      { id: createStepId(20, 5), lessonId: createLessonId(20), stepOrder: 5, stepType: 'question', prompt: 'Lời cảm ơn', correctAnswer: 'cảm ơn' },
    ],
  },
];
