import type { CatalogLessonEntry } from '../seed-lessons';
import { createLessonId, createStepId } from './literacy';

export const STORIES_LESSONS: CatalogLessonEntry[] = [
  // Lesson 11: Rùa và Thỏ: Bài học về tính kiên trì
  {
    lesson: {
      id: createLessonId(11),
      title: 'Rùa và Thỏ: Bài học kiên trì',
      subject: 'Đọc hiểu & Truyện',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 15,
      isPublished: true,
      content: JSON.stringify({
        track: 'stories_comprehension',
        ageBand: '6-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Câu chuyện ngụ ngôn quen thuộc',
        description: 'Đọc truyện Rùa và Thỏ, tìm hiểu ý nghĩa của sự chăm chỉ, không chủ quan kiêu ngạo.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '5.0',
        steps: [
          {
            id: createStepId(11, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Vì sao bạn Thỏ lại bị thua bạn Rùa trong cuộc thi chạy?',
            instruction: 'Tìm nguyên nhân chính khiến Thỏ thất bại.',
            helper: 'Thỏ mải vui chơi và nằm ngủ dưới gốc cây.',
            explanation: 'Thỏ chủ quan, kiêu ngạo và nằm ngủ quên trên đường chạy.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-ngu', label: 'Thỏ chủ quan và ngủ quên dưới gốc cây' },
              { id: 'opt-dauchan', label: 'Thỏ bị đau chân không chạy được' },
              { id: 'opt-quen', label: 'Thỏ quên đường về đích' },
            ],
            canonicalAnswer: 'opt-ngu',
            points: 10,
          },
          {
            id: createStepId(11, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp diễn biến câu chuyện theo đúng trình tự thời gian:',
            instruction: 'Thứ tự từ mở đầu đến kết thúc câu chuyện.',
            helper: 'Thách đấu -> Chạy đua -> Thỏ ngủ -> Rùa về đích.',
            explanation: 'Trình tự: Thỏ chế giễu Rùa -> Cả hai bắt đầu chạy -> Thỏ nằm ngủ -> Rùa cán đích trước.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'ev-1', label: 'Thỏ thách thức và chế giễu Rùa chậm chạp' },
              { id: 'ev-2', label: 'Cuộc thi bắt đầu, Thỏ bỏ xa Rùa' },
              { id: 'ev-3', label: 'Thỏ nằm ngủ say sưa dưới bóng mát' },
              { id: 'ev-4', label: 'Rùa kiên trì từng bước và về đích trước' },
            ],
            canonicalAnswer: ['ev-1', 'ev-2', 'ev-3', 'ev-4'],
            points: 15,
          },
          {
            id: createStepId(11, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những phẩm chất tốt đẹp nào của Rùa giúp Rùa chiến thắng?',
            instruction: 'Chọn tất cả các đức tính đáng khen ngợi của Rùa.',
            helper: 'Rùa không nản lòng dù biết mình chậm.',
            explanation: 'Kiên trì, nhẫn nại và không bỏ cuộc là phẩm chất của Rùa.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-kientri', label: 'Kiên trì, không nản chí' },
              { id: 'opt-nhannai', label: 'Chăm chỉ, bền bỉ từng bước' },
              { id: 'opt-kieu', label: 'Kiêu căng, coi thường người khác' },
            ],
            canonicalAnswer: ['opt-kientri', 'opt-nhannai'],
            points: 15,
          },
          {
            id: createStepId(11, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Câu chuyện khuyên chúng ta: "Chậm mà kiên trì, chắc chắn sẽ thành công", đúng hay sai?',
            instruction: 'Xác định bài học đạo đức của truyện.',
            helper: 'Bài học ngụ ngôn nổi tiếng của Aesop.',
            explanation: 'Đúng, sự kiên trì bền bỉ luôn chiến thắng thói kiêu ngạo chủ quan.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(11, 5),
            stepOrder: 5,
            questionType: 'fill_blank',
            prompt: 'Điền từ còn thiếu vào câu thành ngữ: "Có công mài sắt, có ngày nên ..."',
            instruction: 'Gõ từ chỉ kết quả sau quá trình mài giũa kiên trì.',
            helper: 'Cây kim nhỏ dùng để may vá.',
            explanation: 'Câu thành ngữ là: "Có công mài sắt, có ngày nên kim".',
            canonicalAnswer: 'kim',
            acceptedVariants: ['Kim'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(11, 1), lessonId: createLessonId(11), stepOrder: 1, stepType: 'question', prompt: 'Vì sao Thỏ thua Rùa', correctAnswer: 'opt-ngu' },
      { id: createStepId(11, 2), lessonId: createLessonId(11), stepOrder: 2, stepType: 'question', prompt: 'Sắp xếp diễn biến truyện Rùa và Thỏ', correctAnswer: JSON.stringify(['ev-1', 'ev-2', 'ev-3', 'ev-4']) },
      { id: createStepId(11, 3), lessonId: createLessonId(11), stepOrder: 3, stepType: 'question', prompt: 'Phẩm chất tốt đẹp của Rùa', correctAnswer: JSON.stringify(['opt-kientri', 'opt-nhannai']) },
      { id: createStepId(11, 4), lessonId: createLessonId(11), stepOrder: 4, stepType: 'question', prompt: 'Bài học ngụ ngôn', correctAnswer: 'true' },
      { id: createStepId(11, 5), lessonId: createLessonId(11), stepOrder: 5, stepType: 'question', prompt: 'Có công mài sắt có ngày nên ...', correctAnswer: 'kim' },
    ],
  },

  // Lesson 12: Sự tích Bánh chưng, Bánh giầy
  {
    lesson: {
      id: createLessonId(12),
      title: 'Sự tích Bánh chưng Bánh giầy',
      subject: 'Đọc hiểu & Truyện',
      gradeLevel: 'Lớp 1 - 3',
      estimatedMinutes: 16,
      isPublished: true,
      content: JSON.stringify({
        track: 'stories_comprehension',
        ageBand: '6-9 tuổi',
        difficulty: 'Trung bình',
        subtitle: 'Truyền thuyết Lang Liêu và lòng hiếu thảo',
        description: 'Tìm hiểu nguồn gốc của hai món bánh cổ truyền tượng trưng cho Trời và Đất ngày Tết.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '4.9',
        steps: [
          {
            id: createStepId(12, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Ai là người làm ra chiếc bánh chưng và bánh giầy dâng lên Vua Hùng?',
            instruction: 'Chọn tên chàng hoàng tử hiền lành trong câu chuyện.',
            helper: 'Chàng hoàng tử thứ mười tám chăm chỉ làm ruộng.',
            explanation: 'Hoàng tử Lang Liêu là người tạo ra hai thứ bánh quý giá này.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-langlieu', label: 'Chàng Lang Liêu' },
              { id: 'opt-anthiem', label: 'Mai An Tiêm' },
              { id: 'opt-thachsanh', label: 'Thạch Sanh' },
            ],
            canonicalAnswer: 'opt-langlieu',
            points: 10,
          },
          {
            id: createStepId(12, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Bánh chưng hình vuông và bánh giầy hình tròn tượng trưng cho điều gì?',
            instruction: 'Quan niệm của người xưa về Đất và Trời.',
            helper: 'Đất vuông, Trời tròn.',
            explanation: 'Bánh chưng vuông tượng trưng cho Đất, bánh giầy tròn tượng trưng cho Trời.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-dat-troi', label: 'Bánh chưng tượng trưng cho Đất, bánh giầy tượng trưng cho Trời' },
              { id: 'opt-troi-dat', label: 'Bánh chưng tượng trưng cho Trời, bánh giầy tượng trưng cho Đất' },
              { id: 'opt-bien-nui', label: 'Tượng trưng cho Biển và Núi' },
            ],
            canonicalAnswer: 'opt-dat-troi',
            points: 10,
          },
          {
            id: createStepId(12, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Nguyên liệu chính để Lang Liêu làm bánh chưng gồm những gì?',
            instruction: 'Chọn các nguyên liệu nông sản quen thuộc.',
            helper: 'Hạt ngọc của đồng ruộng Việt Nam.',
            explanation: 'Gạo nếp, đậu xanh và thịt lợn gói lá dong là nguyên liệu truyền thống.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-gaonep', label: 'Gạo nếp dẻo thơm' },
              { id: 'opt-dauxanh', label: 'Đậu xanh và thịt' },
              { id: 'opt-socola', label: 'Bột sô-cô-la' },
            ],
            canonicalAnswer: ['opt-gaonep', 'opt-dauxanh'],
            points: 15,
          },
          {
            id: createStepId(12, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Bánh chưng và bánh giầy thường được người Việt Nam làm vào dịp Tết Nguyên Đán, đúng hay sai?',
            instruction: 'Liên hệ với phong tục ngày Tết cổ truyền.',
            helper: 'Ngày Tết gia đình sum vầy gói bánh chưng bên bếp lửa.',
            explanation: 'Đúng, bánh chưng là biểu tượng ẩm thực không thể thiếu của Tết cổ truyền.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(12, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Loại lá nào màu xanh thường được dùng để gói bánh chưng? (Gõ: lá dong hoặc lá chuối)',
            instruction: 'Nhập tên loại lá truyền thống gói bánh chưng.',
            helper: 'Lá có bản rộng, màu xanh mát.',
            explanation: 'Lá dong (hoặc lá chuối) được dùng để gói bánh chưng.',
            canonicalAnswer: 'lá dong',
            acceptedVariants: ['la dong', 'lá chuối', 'la chuoi'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(12, 1), lessonId: createLessonId(12), stepOrder: 1, stepType: 'question', prompt: 'Người làm ra bánh chưng bánh giầy', correctAnswer: 'opt-langlieu' },
      { id: createStepId(12, 2), lessonId: createLessonId(12), stepOrder: 2, stepType: 'question', prompt: 'Ý nghĩa Đất Trời của bánh', correctAnswer: 'opt-dat-troi' },
      { id: createStepId(12, 3), lessonId: createLessonId(12), stepOrder: 3, stepType: 'question', prompt: 'Nguyên liệu bánh chưng', correctAnswer: JSON.stringify(['opt-gaonep', 'opt-dauxanh']) },
      { id: createStepId(12, 4), lessonId: createLessonId(12), stepOrder: 4, stepType: 'question', prompt: 'Bánh chưng ngày Tết', correctAnswer: 'true' },
      { id: createStepId(12, 5), lessonId: createLessonId(12), stepOrder: 5, stepType: 'question', prompt: 'Lá gói bánh chưng', correctAnswer: 'lá dong' },
    ],
  },

  // Lesson 13: Cây khế và bài học về lòng tham
  {
    lesson: {
      id: createLessonId(13),
      title: 'Cây khế và bài học về lòng tham',
      subject: 'Đọc hiểu & Truyện',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 14,
      isPublished: true,
      content: JSON.stringify({
        track: 'stories_comprehension',
        ageBand: '6-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Ăn một quả khế, trả một cục vàng',
        description: 'Bài học về lối sống nhân hậu, không tham lam qua câu chuyện cổ tích quen thuộc.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '4.8',
        steps: [
          {
            id: createStepId(13, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Con chim thần dặn người em may chiếc túi mấy gang để đựng vàng?',
            instruction: 'Nhớ lại câu nói nổi tiếng của chim thần.',
            helper: '"Ăn một quả khế, trả một cục vàng, may túi ... gang, mang đi mà đựng".',
            explanation: 'Chim dặn may túi ba gang.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-3gang', label: 'Túi ba gang' },
              { id: 'opt-9gang', label: 'Túi chín gang' },
              { id: 'opt-12gang', label: 'Túi mười hai gang' },
            ],
            canonicalAnswer: 'opt-3gang',
            points: 10,
          },
          {
            id: createStepId(13, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Kết cục buồn của người anh tham lam là gì?',
            instruction: 'Điều gì đã xảy ra với người anh khi may túi quá to?',
            helper: 'Túi vàng quá nặng làm chim chao đảo trên biển.',
            explanation: 'Vì quá tham lam nhét đầy vàng, túi nặng khiến người anh rơi xuống biển.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-roi-bien', label: 'Bị rơi xuống biển vì túi vàng quá nặng' },
              { id: 'opt-giau-co', label: 'Trở nên giàu có nhất làng' },
              { id: 'opt-chim-giup', label: 'Được chim thần tặng thêm vàng' },
            ],
            canonicalAnswer: 'opt-roi-bien',
            points: 10,
          },
          {
            id: createStepId(13, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Tính cách của người em trong câu chuyện Cây khế như thế nào?',
            instruction: 'Chọn các từ ngữ miêu tả đúng người em.',
            helper: 'Người em đối xử với chim và anh trai thế nào?',
            explanation: 'Người em hiền lành, thật thà và chăm chỉ.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-hien-lanh', label: 'Hiền lành, nhân hậu' },
              { id: 'opt-that-tha', label: 'Thật thà, chăm chỉ' },
              { id: 'opt-tham-lam', label: 'Tham lam, ích kỷ' },
            ],
            canonicalAnswer: ['opt-hien-lanh', 'opt-that-tha'],
            points: 15,
          },
          {
            id: createStepId(13, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Câu chuyện Cây khế dạy chúng ta không nên tham lam và phải biết yêu thương sẻ chia, đúng hay sai?',
            instruction: 'Xác định bài học đạo đức.',
            helper: 'Tham thì thâm, nhân hậu sẽ gặp lành.',
            explanation: 'Đúng, người ở hiền gặp lành, kẻ tham lam sẽ gặt quả đắng.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(13, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Người anh tham lam đã may chiếc túi mấy gang? (Gõ chữ hoặc số)',
            instruction: 'Nhập số gang tay túi của người anh.',
            helper: 'Gấp ba lần túi của người em.',
            explanation: 'Người anh may túi chín gang.',
            canonicalAnswer: '9 gang',
            acceptedVariants: ['chín gang', '9', 'chin gang'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(13, 1), lessonId: createLessonId(13), stepOrder: 1, stepType: 'question', prompt: 'Túi chim thần dặn người em', correctAnswer: 'opt-3gang' },
      { id: createStepId(13, 2), lessonId: createLessonId(13), stepOrder: 2, stepType: 'question', prompt: 'Kết cục của người anh', correctAnswer: 'opt-roi-bien' },
      { id: createStepId(13, 3), lessonId: createLessonId(13), stepOrder: 3, stepType: 'question', prompt: 'Tính cách của người em', correctAnswer: JSON.stringify(['opt-hien-lanh', 'opt-that-tha']) },
      { id: createStepId(13, 4), lessonId: createLessonId(13), stepOrder: 4, stepType: 'question', prompt: 'Bài học đạo đức', correctAnswer: 'true' },
      { id: createStepId(13, 5), lessonId: createLessonId(13), stepOrder: 5, stepType: 'question', prompt: 'Túi người anh may', correctAnswer: '9 gang' },
    ],
  },

  // Lesson 14: Thạch Sanh dũng cảm diệt Chằn tinh
  {
    lesson: {
      id: createLessonId(14),
      title: 'Thạch Sanh: Lòng dũng cảm và chính trực',
      subject: 'Đọc hiểu & Truyện',
      gradeLevel: 'Lớp 2 - 3',
      estimatedMinutes: 15,
      isPublished: true,
      content: JSON.stringify({
        track: 'stories_comprehension',
        ageBand: '7-9 tuổi',
        difficulty: 'Trung bình',
        subtitle: 'Người dũng sĩ gốc cây đa',
        description: 'Noi gương chàng Thạch Sanh quả cảm, sẵn sàng xả thân cứu người gặp hoạn nạn.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '4.9',
        steps: [
          {
            id: createStepId(14, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Vật báu nào của Thạch Sanh có thể gảy lên khúc nhạc hóa giải hận thù?',
            instruction: 'Chọn món đồ thần kỳ của Thạch Sanh.',
            helper: '"Đàn kêu tích tịch tình tang...".',
            explanation: 'Cây đàn thần của Thạch Sanh có thể vang lên khúc nhạc hòa bình.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-dan-than', label: 'Cây đàn thần' },
              { id: 'opt-guom-than', label: 'Thanh gươm thần' },
              { id: 'opt-chiec-ao', label: 'Chiếc áo giáp vàng' },
            ],
            canonicalAnswer: 'opt-dan-than',
            points: 10,
          },
          {
            id: createStepId(14, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Ai là người luôn mưu mô cướp công của Thạch Sanh?',
            instruction: 'Tìm nhân vật phản diện xảo quyệt trong truyện.',
            helper: 'Người mẹ con làm nghề bán rượu.',
            explanation: 'Lý Thông là kẻ gian xảo cướp công giết Chằn tinh của Thạch Sanh.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-ly-thong', label: 'Lý Thông' },
              { id: 'opt-chan-tinh', label: 'Chằn tinh' },
              { id: 'opt-dai-bang', label: 'Đại bàng' },
            ],
            canonicalAnswer: 'opt-ly-thong',
            points: 10,
          },
          {
            id: createStepId(14, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Những chiến công lẫy lừng nào là của Thạch Sanh?',
            instruction: 'Chọn tất cả các chiến công của chàng.',
            helper: 'Diệt quái vật trừ hại cho dân lành.',
            explanation: 'Diệt Chằn tinh và bắn rơi Đại bàng cứu công chúa là chiến công của Thạch Sanh.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-diet-chantinh', label: 'Diệt Chằn tinh' },
              { id: 'opt-ban-daibang', label: 'Bắn rơi Đại bàng cứu công chúa' },
              { id: 'opt-bat-ca-vang', label: 'Bắt cá vàng khổng lồ' },
            ],
            canonicalAnswer: ['opt-diet-chantinh', 'opt-ban-daibang'],
            points: 15,
          },
          {
            id: createStepId(14, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Niêu cơm thần của Thạch Sanh dù ăn mãi nhưng không bao giờ vơi cạn, đúng hay sai?',
            instruction: 'Nhớ lại chi tiết khao quân 18 nước chư hầu.',
            helper: 'Niêu cơm nhỏ bé mà nuôi đủ muôn quân.',
            explanation: 'Đúng, niêu cơm thần tượng trưng cho sự no ấm, bao dung của người Việt.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(14, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Thạch Sanh sống cùng chiếc búa dưới gốc cây cổ thụ nào? (Gõ tên loài cây)',
            instruction: 'Nhập tên loài cây nơi Thạch Sanh sinh sống.',
            helper: 'Cây đa đầu làng.',
            explanation: 'Thạch Sanh sống dưới gốc cây đa.',
            canonicalAnswer: 'cây đa',
            acceptedVariants: ['đa', 'cay da', 'Cây đa'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(14, 1), lessonId: createLessonId(14), stepOrder: 1, stepType: 'question', prompt: 'Vật báu cây đàn thần', correctAnswer: 'opt-dan-than' },
      { id: createStepId(14, 2), lessonId: createLessonId(14), stepOrder: 2, stepType: 'question', prompt: 'Kẻ cướp công Thạch Sanh', correctAnswer: 'opt-ly-thong' },
      { id: createStepId(14, 3), lessonId: createLessonId(14), stepOrder: 3, stepType: 'question', prompt: 'Chiến công của Thạch Sanh', correctAnswer: JSON.stringify(['opt-diet-chantinh', 'opt-ban-daibang']) },
      { id: createStepId(14, 4), lessonId: createLessonId(14), stepOrder: 4, stepType: 'question', prompt: 'Niêu cơm thần ăn mãi không vơi', correctAnswer: 'true' },
      { id: createStepId(14, 5), lessonId: createLessonId(14), stepOrder: 5, stepType: 'question', prompt: 'Gốc cây Thạch Sanh ở', correctAnswer: 'cây đa' },
    ],
  },

  // Lesson 15: Cô bé quàng khăn đỏ: Lắng nghe lời mẹ
  {
    lesson: {
      id: createLessonId(15),
      title: 'Khăn đỏ nghe lời mẹ dặn',
      subject: 'Đọc hiểu & Truyện',
      gradeLevel: 'Mầm non - Lớp 1',
      estimatedMinutes: 12,
      isPublished: true,
      content: JSON.stringify({
        track: 'stories_comprehension',
        ageBand: '5-7 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Bài học cảnh giác và nghe lời người lớn',
        description: 'Hiểu được tầm quan trọng của việc không đi la cà và cảnh giác trước người lạ nguy hiểm.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '4.9',
        steps: [
          {
            id: createStepId(15, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Trước khi Khăn Đỏ vào rừng thăm bà, mẹ đã dặn Khăn Đỏ điều gì?',
            instruction: 'Tìm lời dặn dò quan trọng của người mẹ.',
            helper: 'Mẹ dặn đi đường thẳng, không được la cà.',
            explanation: 'Mẹ dặn đi đường thẳng, không được la cà hái hoa bắt bướm.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-khong-laca', label: 'Đi thẳng một mạch, không được la cà rẽ ngang' },
              { id: 'opt-hai-hoa', label: 'Cứ hái hoa vui chơi thoải mái' },
              { id: 'opt-trochuyen', label: 'Nói chuyện vui vẻ với chó sói' },
            ],
            canonicalAnswer: 'opt-khong-laca',
            points: 10,
          },
          {
            id: createStepId(15, 2),
            stepOrder: 2,
            questionType: 'single_choice',
            prompt: 'Ai đã dũng cảm cứu Khăn Đỏ và bà cụ thoát khỏi bụng sói gian ác?',
            instruction: 'Chọn người anh hùng tốt bụng giải cứu hai bà cháu.',
            helper: 'Bác thợ săn đi ngang qua nhà bà.',
            explanation: 'Bác thợ săn tốt bụng đã cứu thoát hai bà cháu.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-tho-san', label: 'Bác thợ săn tốt bụng' },
              { id: 'opt-chu-tho', label: 'Chú thỏ trắng' },
              { id: 'opt-bac-gau', label: 'Bác gấu đen' },
            ],
            canonicalAnswer: 'opt-tho-san',
            points: 10,
          },
          {
            id: createStepId(15, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Khi gặp người lạ rủ đi chơi hoặc cho kẹo, bé nên làm gì?',
            instruction: 'Chọn các hành vi an toàn và đúng đắn.',
            helper: 'Bảo vệ bản thân trước nguy hiểm.',
            explanation: 'Bé phải từ chối ngay, chạy về phía người thân hoặc hô to cầu cứu.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-tuchoi', label: 'Lắc đầu từ chối dứt khoát' },
              { id: 'opt-chay-ve-me', label: 'Chạy ngay về phía cha mẹ hoặc thầy cô' },
              { id: 'opt-di-theo', label: 'Đi theo người lạ ngay' },
            ],
            canonicalAnswer: ['opt-tuchoi', 'opt-chay-ve-me'],
            points: 15,
          },
          {
            id: createStepId(15, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Nghe lời cha mẹ dặn dò giúp các bạn nhỏ luôn được an toàn, đúng hay sai?',
            instruction: 'Xác định bài học đạo đức.',
            helper: 'Cha mẹ luôn muốn những điều tốt đẹp và an toàn nhất cho con.',
            explanation: 'Đúng, vâng lời người lớn là cách tự bảo vệ mình tốt nhất.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(15, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Chiếc khăn trùm đầu của cô bé trong truyện có màu gì? (Gõ tên màu)',
            instruction: 'Nhập màu sắc chiếc khăn trùm đầu.',
            helper: 'Màu đỏ rực rỡ.',
            explanation: 'Cô bé quàng chiếc khăn màu đỏ.',
            canonicalAnswer: 'đỏ',
            acceptedVariants: ['màu đỏ', 'do', 'mau do', 'Đỏ'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(15, 1), lessonId: createLessonId(15), stepOrder: 1, stepType: 'question', prompt: 'Lời mẹ dặn Khăn Đỏ', correctAnswer: 'opt-khong-laca' },
      { id: createStepId(15, 2), lessonId: createLessonId(15), stepOrder: 2, stepType: 'question', prompt: 'Người cứu hai bà cháu', correctAnswer: 'opt-tho-san' },
      { id: createStepId(15, 3), lessonId: createLessonId(15), stepOrder: 3, stepType: 'question', prompt: 'Ứng xử khi gặp người lạ', correctAnswer: JSON.stringify(['opt-tuchoi', 'opt-chay-ve-me']) },
      { id: createStepId(15, 4), lessonId: createLessonId(15), stepOrder: 4, stepType: 'question', prompt: 'Nghe lời cha mẹ', correctAnswer: 'true' },
      { id: createStepId(15, 5), lessonId: createLessonId(15), stepOrder: 5, stepType: 'question', prompt: 'Màu khăn quàng', correctAnswer: 'đỏ' },
    ],
  },

  // Lesson 27: Cậu bé Tích Chu: Lòng hiếu thảo và tình yêu thương
  {
    lesson: {
      id: createLessonId(27),
      title: 'Cậu bé Tích Chu: Lòng hiếu thảo và tình yêu thương',
      subject: 'Đọc hiểu & Truyện',
      gradeLevel: 'Lớp 1 - 2',
      estimatedMinutes: 14,
      isPublished: true,
      content: JSON.stringify({
        track: 'stories_comprehension',
        ageBand: '6-8 tuổi',
        difficulty: 'Cơ bản',
        subtitle: 'Hành trình vượt khó tìm nước suối tiên cứu bà của cậu bé Tích Chu',
        description: 'Qua câu chuyện cổ tích xúc động về Tích Chu, bé hiểu được tấm lòng yêu thương bao la của bà và bài học về sự hiếu thảo, biết chăm sóc người thân khi ốm đau.',
        image: '/images/lesson-story.png',
        accent: 'peach',
        rating: '5.0',
        steps: [
          {
            id: createStepId(27, 1),
            stepOrder: 1,
            questionType: 'single_choice',
            prompt: 'Vì Tích Chu mải chơi không lấy nước cho bà uống, bà vì quá khát nên đã hóa thành con gì?',
            instruction: 'Chọn con vật mà bà của Tích Chu đã hóa thành.',
            helper: 'Con vật có cánh bay lên trời tìm nước uống.',
            explanation: 'Bà của Tích Chu vì khát nước quá nên đã hóa thành chim vỗ cánh bay đi.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-chim', label: 'Con chim vỗ cánh bay đi' },
              { id: 'opt-ca', label: 'Con cá bơi dưới nước' },
              { id: 'opt-buom', label: 'Con bướm lượn quanh vườn' },
            ],
            canonicalAnswer: 'opt-chim',
            points: 10,
          },
          {
            id: createStepId(27, 2),
            stepOrder: 2,
            questionType: 'ordering',
            prompt: 'Sắp xếp diễn biến câu chuyện Cậu bé Tích Chu theo đúng thứ tự:',
            instruction: 'Sắp xếp các sự việc từ đầu đến cuối câu chuyện.',
            helper: 'Mải chơi -> Hối hận -> Vượt núi tìm nước -> Bà trở lại thành người.',
            explanation: 'Thứ tự đúng: Tích Chu mải chơi -> Bà hóa thành chim -> Tích Chu đi tìm suối tiên -> Bà trở lại thành người.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'tc-mai-choi', label: 'Tích Chu mải chơi, bà bị ốm và khát nước' },
              { id: 'tc-hoa-chim', label: 'Bà hóa thành chim bay đi tìm nước' },
              { id: 'tc-lay-nuoc', label: 'Tích Chu vượt đèo lội suối lấy nước suối tiên' },
              { id: 'tc-doan-tu', label: 'Cho bà uống nước và hai bà cháu đoàn tụ' },
            ],
            canonicalAnswer: ['tc-mai-choi', 'tc-hoa-chim', 'tc-lay-nuoc', 'tc-doan-tu'],
            points: 15,
          },
          {
            id: createStepId(27, 3),
            stepOrder: 3,
            questionType: 'multiple_choice',
            prompt: 'Để cứu bà trở lại thành người, Tích Chu đã thể hiện những phẩm chất tốt đẹp nào?',
            instruction: 'Chọn các phẩm chất tốt của Tích Chu trong chuyến đi.',
            helper: 'Không quản ngại gian khổ và hết lòng vì bà.',
            explanation: 'Tích Chu đã biết ăn năn hối hận, kiên trì và dũng cảm vượt mọi gian lao để cứu bà.',
            image: '/images/lesson-story.png',
            options: [
              { id: 'opt-hoi-han', label: 'Biết ăn năn, hối hận và thương bà sâu sắc' },
              { id: 'opt-dung-cam', label: 'Dũng cảm, không ngại khó khăn đường xa' },
              { id: 'opt-bo-cuoc', label: 'Dễ dàng bỏ cuộc khi gặp suối sâu' },
            ],
            canonicalAnswer: ['opt-hoi-han', 'opt-dung-cam'],
            points: 15,
          },
          {
            id: createStepId(27, 4),
            stepOrder: 4,
            questionType: 'true_false',
            prompt: 'Câu chuyện Cậu bé Tích Chu khuyên các bạn nhỏ phải biết yêu thương, chăm sóc và hiếu thảo với ông bà cha mẹ, đúng hay sai?',
            instruction: 'Nhận xét về ý nghĩa nhân văn của câu chuyện.',
            helper: 'Gia đình luôn là điều quý giá nhất.',
            explanation: 'Đúng, câu chuyện giáo dục lòng hiếu thảo và sự quan tâm đến người thân.',
            canonicalAnswer: true,
            points: 10,
          },
          {
            id: createStepId(27, 5),
            stepOrder: 5,
            questionType: 'short_answer',
            prompt: 'Tích Chu đã lặn lội đến dòng suối nào để lấy nước đem về cho bà uống? (Gõ tên con suối)',
            instruction: 'Nhập tên dòng suối kỳ diệu theo lời dặn của bà Tiên.',
            helper: 'Suối ... ở nơi núi non xa xôi.',
            explanation: 'Đó là dòng suối tiên màu nhiệm.',
            canonicalAnswer: 'suối tiên',
            acceptedVariants: ['Suối tiên', 'Suối Tiên', 'suoi tien'],
            points: 15,
          },
        ],
      }),
    },
    steps: [
      { id: createStepId(27, 1), lessonId: createLessonId(27), stepOrder: 1, stepType: 'question', prompt: 'Bà Tích Chu hóa thành chim', correctAnswer: 'opt-chim' },
      { id: createStepId(27, 2), lessonId: createLessonId(27), stepOrder: 2, stepType: 'question', prompt: 'Sắp xếp diễn biến Cậu bé Tích Chu', correctAnswer: JSON.stringify(['tc-mai-choi', 'tc-hoa-chim', 'tc-lay-nuoc', 'tc-doan-tu']) },
      { id: createStepId(27, 3), lessonId: createLessonId(27), stepOrder: 3, stepType: 'question', prompt: 'Phẩm chất tốt của Tích Chu', correctAnswer: JSON.stringify(['opt-hoi-han', 'opt-dung-cam']) },
      { id: createStepId(27, 4), lessonId: createLessonId(27), stepOrder: 4, stepType: 'question', prompt: 'Ý nghĩa bài học hiếu thảo', correctAnswer: 'true' },
      { id: createStepId(27, 5), lessonId: createLessonId(27), stepOrder: 5, stepType: 'question', prompt: 'Tên con suối tiên', correctAnswer: 'suối tiên' },
    ],
  },
];
