import { NextResponse } from 'next/server';
import { desc, eq } from 'drizzle-orm';
import { db } from '@/db/client';
import { dataDeletionJobs } from '@/db/schema';
import { requireParentSession } from '@/server/auth';
import { assertChildOwned, audit, context, mapDeletion, reauthenticate, SafetyError, safetyErrorResponse } from '@/server/safety';
import { z } from 'zod';

export async function GET() { try { const s = await requireParentSession(); if (s instanceof Response) return s; const { household } = await context(s); const rows = await db.select().from(dataDeletionJobs).where(eq(dataDeletionJobs.householdId, household.id)).orderBy(desc(dataDeletionJobs.createdAt)); return NextResponse.json({ deletionRequests: rows.map(mapDeletion) }); } catch (e) { return safetyErrorResponse(e); } }
const schema = z.object({ scope: z.enum(['child_transcripts', 'emotion_timeline', 'all_child_data', 'entire_account']), childId: z.string().uuid().optional(), reason: z.string().max(1000).optional(), reauthPassword: z.string().optional(), confirmed: z.literal(true) }).strict();
export async function POST(request: Request) { try { const s = await requireParentSession(); if (s instanceof Response) return s; const p = schema.safeParse(await request.json()); if (!p.success) throw new SafetyError(400, 'VALIDATION_FAILED', 'Invalid deletion request.', p.error.flatten().fieldErrors as Record<string, string[]>); const { household } = await context(s); if (p.data.childId) await assertChildOwned(household.id, p.data.childId); if (p.data.scope !== 'entire_account' && !p.data.childId) throw new SafetyError(400, 'VALIDATION_FAILED', 'A child must be selected for this deletion scope.', { childId: ['Required for child data deletion.'] }); await reauthenticate(s.sub, p.data.reauthPassword); const stageNames = p.data.scope === 'child_transcripts' ? ['transcripts'] : p.data.scope === 'emotion_timeline' ? ['emotion_timeline'] : ['transcripts', 'emotion_timeline', 'session_logs', 'profile_metadata']; const stages = stageNames.map((stage) => ({ stage, status: 'pending', detail: 'Awaiting deletion worker.' })); const [row] = await db.insert(dataDeletionJobs).values({ householdId: household.id, requestedByUserId: s.sub, status: 'pending', stagesReport: { request: { scope: p.data.scope, childId: p.data.childId }, stages }, errorMessage: null } as typeof dataDeletionJobs.$inferInsert).returning(); if (!row) throw new Error('Deletion job insert returned no row'); await audit(s.sub, 'data_deletion.requested', 'data_deletion_job', row.id, { scope: p.data.scope, childId: p.data.childId ?? null, reason: p.data.reason ?? null }); const deletion = { ...mapDeletion(row), stages: stages.map((stage) => ({ ...stage, name: stage.stage })) }; return NextResponse.json({ deletion, message: 'Deletion request is recorded and pending. No data has been deleted because no deletion worker is configured.' }, { status: 202 }); } catch (e) { return safetyErrorResponse(e); } }
