import { NextResponse } from 'next/server';
import { db } from '@/db/client';
import { capabilityConsents } from '@/db/schema';
import { requireParentSession } from '@/server/auth';
import { assertChildOwned, audit, consentCapabilities, context, latestConsents, mapConsent, POLICY_VERSION, reauthenticate, SafetyError, safetyErrorResponse } from '@/server/safety';
import { z } from 'zod';

export async function GET(request: Request) { try { const s = await requireParentSession(); if (s instanceof Response) return s; const { household } = await context(s); const childId = new URL(request.url).searchParams.get('childId') ?? undefined; await assertChildOwned(household.id, childId); const consents = (await latestConsents(household.id, childId)).map(mapConsent); const summary = { microphone: false, camera: false, vision: false, screen: false }; for (const c of consents) if (c.granted && c.status === 'granted') summary[c.scope] = true; return NextResponse.json({ consents, summary, policyVersion: POLICY_VERSION }); } catch (e) { return safetyErrorResponse(e); } }

const schema = z.object({ scope: z.enum(['microphone', 'camera', 'vision', 'screen']), granted: z.boolean(), policyVersion: z.string().optional(), childId: z.string().uuid().optional(), notes: z.string().max(500).optional(), reauthPassword: z.string().optional() }).strict();
export async function POST(request: Request) { try { const s = await requireParentSession(); if (s instanceof Response) return s; const parsed = schema.safeParse(await request.json()); if (!parsed.success) throw new SafetyError(400, 'VALIDATION_FAILED', 'Invalid consent request.', parsed.error.flatten().fieldErrors as Record<string, string[]>); const p = parsed.data; const { household } = await context(s); await assertChildOwned(household.id, p.childId); await reauthenticate(s.sub, p.reauthPassword); const capability = consentCapabilities[p.scope]; const latest = (await latestConsents(household.id, p.childId)).find((r) => r.capability === capability); const [row] = await db.insert(capabilityConsents).values({ householdId: household.id, childId: p.childId ?? null, capability, version: (latest?.version ?? 0) + 1, granted: p.granted, grantedAt: p.granted ? new Date() : null, revokedAt: p.granted ? null : new Date(), grantedByUserId: s.sub, metadata: { policyVersion: p.policyVersion ?? POLICY_VERSION, ...(p.notes ? { notes: p.notes } : {}) } as never } as typeof capabilityConsents.$inferInsert).returning(); if (!row) throw new Error('Consent insert returned no row'); await audit(s.sub, 'consent.recorded', 'capability_consent', row.id, { scope: p.scope, granted: p.granted, version: row.version, childId: p.childId }); return NextResponse.json({ consent: mapConsent(row) }, { status: 201 }); } catch (e) { return safetyErrorResponse(e); } }
